# -*- encoding : utf-8 -*-
module HRWA::FilterOptions

  def self.option_list( option_name, selected_values = nil )
    option_list = self.instance_variable_get( '@' + option_name + '_filter_options' )
    
    raise ArgumentError, "No such filter option as #{ option_name }" if option_list.nil?  
    
    option_hash = option_list_to_hash( option_list )
    
    # Early return of full set of options if no selected values are passed
    return option_hash if ( ! selected_values or selected_values.empty? )
  end
  
  def self.option_list_to_hash( option_list )
    option_hash = {}
    option_list.sort.each { | option |
      option_hash[ option ] = false
    }
    return option_hash
  end

  def self.bib_id_options( selected_values = nil )
    return option_list( 'bib_id', selected_values )
  end

  def self.creator_name_options( selected_values = nil )
    return option_list( 'creator_name', selected_values )
  end

  def self.domain_options( selected_values = nil )
    return option_list( 'domain', selected_values )
  end
  
  def self.geographic_focus_options( selected_values = nil )
    return option_list( 'geographic_focus', selected_values )
  end
  
  def self.language_options( selected_values = nil )
    return option_list( 'language', selected_values )
  end
  
  def self.organization_based_in_options( selected_values = nil )
    return option_list( 'organization_based_in', selected_values )
  end
  
  def self.organization_type_options( selected_values = nil )
    return option_list( 'organization_type', selected_values )
  end

  @bib_id_filter_options = [
    "4191511",
    "4751601",
    "5316489",
    "5355337",
    "5421151",
    "5533057",
    "5550172",
    "5571653",
    "6952107",
    "7033263",
    "7033264",
    "7033265",
    "7033266",
    "7033267",
    "7033268",
    "7033269",
    "7033270",
    "7038247",
    "7038248",
    "7038249",
    "7038250",
    "7038252",
    "7038253",
    "7038254",
    "7038255",
    "7038257",
    "7038258",
    "7038259",
    "7038261",
    "7038262",
    "7038263",
    "7038264",
    "7038266",
    "7038267",
    "7038269",
    "7038270",
    "7038273",
    "7038274",
    "7038286",
    "7038287",
    "7038313",
    "7038315",
    "7038318",
    "7038324",
    "7038327",
    "7038329",
    "7038337",
    "7038338",
    "7038343",
    "7038349",
    "7038350",
    "7038351",
    "7038358",
    "7038360",
    "7038369",
    "7038371",
    "7038373",
    "7038374",
    "7038375",
    "7038377",
    "7038378",
    "7038379",
    "7038380",
    "7038381",
    "7038382",
    "7038383",
    "7038386",
    "7038387",
    "7038388",
    "7038393",
    "7038397",
    "7038398",
    "7038399",
    "7038400",
    "7038402",
    "7038403",
    "7038404",
    "7038405",
    "7038406",
    "7038407",
    "7038409",
    "7038410",
    "7038411",
    "7038412",
    "7038413",
    "7038417",
    "7038418",
    "7038429",
    "7038438",
    "7038439",
    "7038443",
    "7038447",
    "7038450",
    "7038451",
    "7038455",
    "7038456",
    "7038458",
    "7038459",
    "7038462",
    "7038465",
    "7038466",
    "7038467",
    "7038487",
    "7038488",
    "7038489",
    "7038491",
    "7038492",
    "7038493",
    "7038494",
    "7038496",
    "7038497",
    "7038498",
    "7038499",
    "7038500",
    "7038501",
    "7038502",
    "7038509",
    "7038518",
    "7038521",
    "7038523",
    "7038527",
    "7038532",
    "7038537",
    "7038540",
    "7038541",
    "7038542",
    "7038543",
    "7038544",
    "7038545",
    "7038546",
    "7038548",
    "7038549",
    "7038550",
    "7038565",
    "7038567",
    "7038582",
    "7038586",
    "7038594",
    "7038602",
    "7038604",
    "7038608",
    "7038617",
    "7038618",
    "7038622",
    "7038626",
    "7038632",
    "7038633",
    "7038639",
    "7038644",
    "7038648",
    "7038649",
    "7038650",
    "7038651",
    "7038652",
    "7038653",
    "7038655",
    "7038656",
    "7038657",
    "7038659",
    "7038660",
    "7038661",
    "7038662",
    "7038665",
    "7038669",
    "7038672",
    "7038673",
    "7038674",
    "7038675",
    "7038677",
    "7038678",
    "7038679",
    "7038680",
    "7038681",
    "7038683",
    "7038685",
    "7038689",
    "7038691",
    "7038693",
    "7038694",
    "7038697",
    "7038705",
    "7038710",
    "7038721",
    "7038723",
    "7038724",
    "7038737",
    "7038742",
    "7038744",
    "7038748",
    "7038755",
    "7038757",
    "7038760",
    "7038761",
    "7038762",
    "7038763",
    "7038780",
    "7038783",
    "7038786",
    "7038790",
    "7038792",
    "7038793",
    "7038797",
    "7038800",
    "7038803",
    "7038805",
    "7038807",
    "7038808",
    "7038811",
    "7038814",
    "7038815",
    "7038819",
    "7038820",
    "7410021",
    "7410095",
    "7731591",
    "7731800",
    "7731836",
    "7732061",
    "7732064",
    "7732065",
    "7732066",
    "7732067",
    "7757146",
    "7757269",
    "7771968",
    "7799772",
    "7799921",
    "7799940",
    "7800011",
    "7800014",
    "7803400",
    "7809241",
    "7813033",
    "7813804",
    "7813805",
    "7813806",
    "7813807",
    "7815173",
    "7815764",
    "7815770",
    "7819636",
    "7819664",
    "7819678",
    "7819711",
    "7820127",
    "7822594",
    "7822959",
    "7824247",
    "7832247",
    "7834145",
    "7834591",
    "7837629",
    "7839243",
    "7839371",
    "7876812",
    "7876840",
    "7885006",
    "7885012",
    "7885543",
    "7885570",
    "7886427",
    "7887220",
    "7888713",
    "7888758",
    "7890025",
    "7890675",
    "7890712",
    "7890773",
    "7900280",
    "7901541",
    "7902541",
    "7902567",
    "7904717",
    "7904970",
    "7905016",
    "7905284",
    "7905317",
    "7905623",
    "7905779",
    "7905840",
    "7923757",
    "7928882",
    "7952294",
    "7960030",
    "7971722",
    "8011158",
    "8067914",
    "8163119",
    "8179176",
    "8229614",
    "8257091",
    "8263078",
    "8281930",
    "8287713",
    "8408166",
    "8408203",
    "8408294",
    "8409019",
    "8412117",
    "8414984",
    "8415142",
    "8415331",
    "8415370",
    "8415458",
    "8438804",
    "8438858",
    "8446737",
    "8446829",
    "8446849",
    "8446886",
    "8448889",
    "8455301",
    "8455464",
    "8455680",
    "8456088",
    "8459920",
    "8460274",
    "8481136",
    "8502012",
    "8502198",
    "8513355",
    "8513367",
    "8513460",
    "8519721",
    "8519768",
    "8519817",
    "8535465",
    "8536054",
    "8539206",
    "8539218",
    "8539234",
    "8539239",
    "8539259",
    "8539378",
    "8539924",
    "8539972",
    "8540001",
    "8540054",
    "8540401",
    "8540825",
    "8540838",
    "8540895",
    "8541975",
    "8557218",
    "8585473",
    "8586003",
    "8602383",
    "8602539",
    "8602577",
    "8602843",
    "8616290",
    "8616335",
    "8616886",
    "8618396",
    "8618609",
    "8644505",
    "8703322",
    "8775601",
    "8775896",
    "8960390",
  ]

  @creator_name_filter_options = [
    "880-01 5.18 Kinyo?m Chaedan (Korea)",
    "880-03 Markaz al-MisÌ£riÌ? li-HÌ£uquÌ?q al-MarÊ¾ah",
    "Access to Justice (Organization : Nigeria)",
    "AcÌ§aÌ?o Brasileira pela NutricÌ§aÌ?o e Direitos Humanos",
    "Adalah (Organization)",
    "Africa Internally Displaced Persons Voice (Organization)",
    "African Centre for Democracy and Human Rights Studies",
    "Agudah li-zekhuyot ezrah? be-Yis´ra?el",
    "Al-Dameer Association for Human Rights",
    "Algeria-Watch (Organization)",
    "Amigos de las Mujeres de Juarez",
    "Amnesty International. Canadian Section-English-Speaking",
    "Amnesty International Chile",
    "Amnesty International C?R",
    "Amnesty International Danmark",
    "Amnesty International France",
    "Amnesty International. F?roya deild",
    "Amnesty International-Ghana",
    "Amnesty International. Greek Section",
    "Amnesty International Hong Kong",
    "Amnesty International Hrvatske",
    "Amnesty International. IÌslandsdeild",
    "Amnesty International. International Secretariat",
    "Amnesty International. Irish Section",
    "Amnesty International Luxembourg",
    "Amnesty International MagyarorszaÌg",
    "Amnesty International. Mauritius Section",
    "Amnesty International Moldova",
    "Amnesty International Nepal",
    "Amnesty International. Nihon Shibu",
    "Amnesty International Norge",
    "Amnesty International O¨sterreich",
    "Amnesty International Pilipinas",
    "Amnesty International Polska",
    "Amnesty International. Schweizer Sektion",
    "Amnesty International. Secc¸a~o Portuguesa",
    "Amnesty International. Seccio´n Argentina",
    "Amnesty International. Seccio´n Espano~la",
    "Amnesty International. Seccio´n Paraguaya",
    "Amnesty International. Seccio´n Peruana",
    "Amnesty International. Seccio´n Uruguay",
    "Amnesty International. Section Togo",
    "Amnesty International Slovensko",
    "Amnesty International South Africa",
    "Amnesty International. Svenska sektionen",
    "Amnesty International v Ukrai¨ni",
    "Amnesty Suomessa",
    "Amnisti´a Internacional Bolivia",
    "Amnisti´a Internacional Puerto Rico",
    "AmnistiÌa Internacional MeÌxico",
    "Anti Caste Discrimination Alliance",
    "Arab Association for Human Rights (Israel)",
    "Argentina. Defensor del Pueblo de la Nacio´n",
    "Asian Centre for Human Rights",
    "Asian Federation Against Involuntary Disappearances (Philippines)",
    "Asian Forum for Human Rights and Development",
    "Asian Human Rights Commission",
    "Asia Pacific Forum of National Human Rights Institutions",
    "AsociacioÌn Paz con Dignidad",
    "Asociacio´n de Abuelas de Plaza de Mayo",
    "Asociacio´n de Familiares de Presos y Desaparecidos Saharauis",
    "Asociacio´n Paz con Dignidad",
    "Asociacio´n por los Derechos Civiles (Buenos Aires, Argentina)",
    "Assistance Association for Political Prisoners (Burma)",
    "Association for the Prevention of Torture",
    "Association for Women's Rights in Development",
    "Association of Women for Action and Research",
    "Association pour le respect des droits de l'homme aÌ? Djibouti",
    "Association sahraouie des victimes des violations graves des droits de l'homme commises par l'Etat du Maroc",
    "Associazione per la tutela dei diritti umani del popolo Eritreo",
    "Assot?s?iat?s?ii?a? korennykh malochislennykh narodov Severa, Sibiri i Dal'nego Vostoka Rossii?skoi? Federat?s?ii",
    "Australian Human Rights Commission",
    "Austria. Volksanwaltschaft",
    "Aza¨rbaycan Respublikasinin I?nsan Hu¨quqlari U¨zra¨ Mu¨va¨kkili",
    "Baheyya",
    "BAOBAB for Women's Human Rights",
    "Barna¯maj al-?Arabi¯ li-Nushat?a¯? H?uqu¯q al-Insa¯n",
    "Belaruski khel'sinski kamite?t",
    "Beogradski centar za ljudska prava",
    "Bermuda Ombudsman",
    "Be-tselem (Organization : Jerusalem)",
    "Bimkom (Organization : Jerusalem)",
    "Bod-kyi ?Gro-ba Mi?i-thob-than? dan? Man?-gtso-?phel-rgyas Lte-gnas-khan? (Dharmsa¯la, India)",
    "Breakthrough (Organization)",
    "Burma Campaign UK",
    "Burma Lawyers' Council",
    "Campaign for Good Governance",
    "Canadian Friends of Burma",
    "Catholic Church. Archdiocese of Santiago (Chile). Vicari´a de la Solidaridad. Fundacio´n Documentacio´n y Archivo",
    "Center for Democracy &amp; Human Rights in Saudi Arabia",
    "Center for Democracy and Reconciliation in Southeast Europe",
    "Center for Economic and Social Rights",
    "Center for Justice and Accountability",
    "Center for Justice and International Law",
    "Centre for Democratic Development, Research and Training",
    "Centre for Human Rights &amp; Rehabilitation (Lilongwe, Malawi)",
    "Centre for the Study of Violence and Reconciliation",
    "Centre for War Victims and Human Rights",
    "Centro de Derechos Humanos Miguel Agusti´n Pro Jua´rez",
    "Centro de Derechos Humanos y Ambiente",
    "Centro de Estudios Legales y Sociales (Argentina)",
    "Centro de Estudios Sociales Padre Juan Montalvo, SJ",
    "Centro de Justicia para la Paz y el Desarrollo",
    "Centro para la Accio´n Legal en Derechos Humanos",
    "Child Rights Information &amp; Documentation Centre",
    "Chile Information Project",
    "Chinsil, Hwahae ru?l wihan Kwago?sa Cho?ngni Wiwo?nhoe",
    "Citizenship Rights in Africa Initiative",
    "Coalition for an Effective African Court on Human and Peoples' Rights",
    "Collectif des associations contre l'impunite´ au Togo",
    "Comisio´n Mexicana de Defensa y Promocio´n de los Derechos Humanos",
    "Comissa~o de Acolhimento, Verdade, e Reconciliac?a~o Timor Leste",
    "Comite´ de Familiares de Detenidos-Desaparecidos en Honduras",
    "ComiteÌ para la Defensa de los Derechos Humanos en Honduras",
    "Comite´ pour le respect des liberte´s et des droits de l'homme en Tunisie",
    "Comite´ se´ne´galaise des droits de l'homme",
    "Commissie Gelijke Behandeling (Netherlands)",
    "Commission nationale des droits de l'homme (Togo)",
    "Committee to Protect Journalists",
    "Community Appraisal &amp; Motivation Program",
    "CONECTAS Direitos Humanos",
    "Coordinadora de Derechos Humanos del Paraguay",
    "Coordinadora Nacional de Derechos Humanos (Peru)",
    "Corporacio´n de Promocio´n y Defensa de los Derechos del Pueblo (Chile)",
    "Costa Rica. Defensori´a de los Habitantes de la Repu´blica",
    "Croatia. Puc?ki pravobranitelj",
    "Cuban Committee for Human Rights",
    "Czech Republic. Ver?ejny´ ochra´nce pra´v",
    "Da Afgha¯nista¯n da Bashar da H?uqu¯qo da Khpalva¯k Kami¯siyu¯n",
    "Darfur Consortium",
    "Defensor del Pueblo (Bolivia)",
    "Defensori´a del Pueblo de la Repu´blica de Panama´",
    "Defensori´a del Pueblo (Ecuador)",
    "Defensori´a del Pueblo (Peru)",
    "DefensoriÌa del Pueblo (Paraguay)",
    "Democracywatch (Organization : Dhaka, Bangladesh)",
    "Deutsches Institut fu¨r Menschenrechte",
    "Diskrimineringsombudsmannen (Sweden)",
    "Ditshwanelo (Organization)",
    "Down to Earth (Organization)",
    "ECPAT International",
    "EdÌ£bhokesiÌ? Phorama (Kathmandu, Nepal)",
    "Electoral Institute of Southern Africa",
    "Empowerment and Rights Institute (China)",
    "Eritrean Human Rights Electronic Archive",
    "European Roma Rights Center",
    "Focus on the Global South (Program)",
    "Forces de libe´ration africaines de Mauritanie",
    "Forum for African Women Educationalists",
    "Foundation for Human Rights Initiative",
    "France. Commission nationale consultative des droits de l'homme",
    "Friends of Tibet, INDIA",
    "Front Line (Organization)",
    "FundacioÌn de Antropologia Forense de Guatemala",
    "Fundacio´n de Ayuda Social de las Iglesias Cristianas",
    "Fundacio´n Regional de Asesori´a en Derechos Humanos",
    "Gabinete de Assessoria Juri´dica as Organizac¸oes Populares",
    "Ghana Center for Democratic Development",
    "Global Alliance against Traffic in Women",
    "Global Witness (Organization)",
    "Great Britain. Equality and Human Rights Commission",
    "Greece. Ethnike¯ Epitrope¯ gia ta Dikaio¯mata tou Anthro¯pou",
    "Greensboro Truth &amp; Community Reconciliation Project",
    "Greensboro Truth &amp; Reconciliation Commission",
    "Guatemala. Procurador de los Derechos Humanos",
    "HakiElimu (Tanzania)",
    "Hay?ah al-Mustaqillah li-H?uqu¯q al-Insa¯n (West Bank)",
    "Hayastani Hanrapetut?yan Mardu Iravunk?neri Pashtpan",
    "HayÊ¾ah al-FilastÌ£iÌ?niÌ?yah al-Mustaqillah li-HÌ£uquÌ?q al-MuwaÌ?tÌ£in",
    "Helsinki Citizens' Assembly. Vanadzor Office",
    "He´ritiers de la justice (Organization)",
    "Honduras. Comisionado Nacional de los Derechos Humanos",
    "Human Rights Centre (T?bilisi, Georgia)",
    "Human Rights Commission of Pakistan",
    "Human Rights Commission of the Maldives",
    "Human Rights Concern Eritrea (Organization)",
    "Human Rights Congress for Bangladesh Minorities",
    "Human Rights Council of Australia Inc",
    "Human Rights Education Institute of Burma",
    "Human Rights First (Organization)",
    "Human Rights First Society",
    "Human Rights Law Network (New Delhi, India)",
    "Hungary. Nemzeti e´s Etnikai Kisebbse´gi Jogok Orsza´ggyu?le´si Biztosa",
    "I-India (Organization)",
    "IÌ?nsan HaklarÄ± Ortak Platformu",
    "India. National Human Rights Commission",
    "INDICT",
    "Indigenous Peoples' Center for Documentation, Research and Information",
    "Indigenous Peoples Council on Biocolonialism",
    "Institute for Democracy in Africa",
    "Institute for Justice and Reconciliation (South Africa)",
    "Institut for menneskerettigheder (Denmark)",
    "Instituto de Estudios Juridico Sociales de la Mujer",
    "Instituto Espacio para la Memoria (Argentina)",
    "International Campaign for Tibet",
    "International Coalition for the Responsibility to Protect",
    "International Commission of Jurists (1952- )",
    "International Commission on Missing Persons",
    "International Committee Against Stoning",
    "International Committee for Democracy in Cuba",
    "International Committee of Solidarity for Political Prisoners in Tunisia",
    "International Crisis Group",
    "International Federation of Health and Human Rights Organisations",
    "International Federation of Iranian Refugees",
    "International Gay and Lesbian Human Rights Commission",
    "International League for Human Rights",
    "International Network for the Rights of Female Victims of Violence in Pakistan",
    "International Service for Human Rights",
    "International Society for Human Rights",
    "International Work Group for Indigenous Affairs",
    "Iran Human Rights Documentation Center",
    "Iraq Foundation",
    "Iraqi Human Rights Group",
    "Islamic Human Rights Commission (Great Britain)",
    "JamÊ»iÌ?yat ShabaÌ?b al-BahÌ£rayn li-HÌ£uquÌ?q al-InsaÌ?n",
    "Jam?i¯yah al-Jali¯l",
    "Jam?i¯yah al-Maghribi¯yah li-H?uqu¯q al-Insa¯n",
    "Jam?i¯yah al-Mis?ri¯yah lil-Nuhu¯d bi-al-Musha¯rakah al-Mujtama?i¯yah",
    "Jam?i¯yah al-Wat?ani¯yah lil-Taghyi¯r (Egypt)",
    "Jesuit Refugee Service",
    "Jesuit Refugee Service/USA",
    "Judicial System Monitoring Programme",
    "Jumma Peoples Network UK",
    "Kadinin I?nsan Haklari--Yeni Co¨zu¨mler",
    "Kenya Human Rights Commission",
    "Kenya National Commission on Human Rights",
    "Khana Kammaka¯n Sitthi Manutsayachon hæ¯ng Cha¯t (Thailand)",
    "Kharkivs'ka pravozakhysna hrupa",
    "Khru¯aikha¯i Patibat Nga¯n Phu¯a Sattri¯ Cha¯o Thai Yai",
    "Khu?nii? E?rkhii?n U?nde?snii? Komiss (Mongolia)",
    "Kituo cha Sheria na Haki za Binadamu (Tanzania)",
    "Komnas HAM (Indonesia)",
    "KosovaLive (Organization)",
    "Kurdish Human Rights Project",
    "Kurdish Women's Rights Watch",
    "Kuru Family of Organisations",
    "Kyrgyz Committee for Human Rights",
    "Lajnat al-Difa¯? ?an H?uqu¯q al-Insa¯n fi¯ Shibh al-Jazi¯rah al-?Arabi¯yah",
    "Land Center for Human Rights (Egypt)",
    "Latin American and Caribbean Committee for the Defense of Women's Rights",
    "Latvian Centre for Human Rights",
    "Law and Society Trust (Sri Lanka)",
    "Law in the Service of Man (Organization : Ra¯m Alla¯h)",
    "Lawyers Centre for Legal Assistance (Sierra Leone)",
    "Lembaga Studi dan Advokasi Masyarakat (Jakarta, Indonesia)",
    "Liberia. Truth and Reconciliation Commission",
    "Ligue burundaise des droits de l'homme",
    "Madre (Organization)",
    "Majhamandal samÌ£rap QbhivadhnÌ? SangamÌ£ (Phnom Penh, Cambodia)",
    "Majlis al-Istisha¯ri¯ li-H?uqu¯q al-Insa¯n (Morocco)",
    "Majlis al-Qawmi¯ li-H?uqu¯q al-Insa¯n (Egypt)",
    "Majlis al-Wat?ani¯ lil-H?urri¯ya¯t bi-Tu¯nis",
    "Malawi. Human Rights Commission",
    "Malawi Human Rights Resource Centre",
    "Malaysia. Suruhanjaya Hak Asasi Manusia Malaysia",
    "Ma¯nava Adhika¯ra tatha¯ Praja¯ta¯ntrika Man~ca (Kathmandu, Nepal)",
    "Markaz al-Filast?i¯ni¯ li-H?uqu¯q al-Insa¯n",
    "Markaz al-Mi¯za¯n li-H?uqu¯q al-Insa¯n (Gaza Strip)",
    "Markaz al-Qa¯hirah li-Dira¯sa¯t H?uqu¯q al-Insa¯n",
    "Markaz al-Tawthi¯q wa-al-I?la¯m wa-al-Takwi¯n fi¯ Maja¯l H?uqu¯q al-Insa¯n",
    "Markaz al-Wat?ani¯ li-H?uqu¯q al-Insa¯n (Jordan)",
    "Markaz ?Amma¯n li-Dira¯sa¯t H?uqu¯q al-Insa¯n",
    "Markaz Andalus li-DiraÌ?saÌ?t al-TasaÌ?muhÌ£ wa-MunaÌ?hadÌ£at al-Ê»Unf",
    "Markaz Hisha¯m Muba¯rak lil-Qa¯nu¯n",
    "Markaz Ra¯m Alla¯h li-Dira¯sa¯t H?uqu¯q al-Insa¯n",
    "Mars?ad al-Yamani¯ li-H?uqu¯q al-Insa¯n",
    "Mazlum-Der (Organization)",
    "Media Foundation for West Africa",
    "Medijski centar Beta",
    "Mexico. Comisio´n Nacional de Derechos Humanos",
    "Minority Rights Group International",
    "MokÌ£ed la-haganat ha-peratÌ£ (Jerusalem)",
    "Morocco. HayÊ¾at al-InsÌ£aÌ?f wa-al-MusÌ£aÌ?lahÌ£ah",
    "Moskovskai?a? khel'sinkskai?a? gruppa",
    "Mouvement contre les armes le´ge`res en Afrique de l'Ouest",
    "Movimento dos Trabalhadores Rurais sem Terra (Brazil)",
    "Mu?assasat al-Mar?ah al-Jadi¯dah (Egypt)",
    "Muba¯darah al-?Arabi¯yah li-Intirnit H?urr",
    "Munaz?z?amah al-?Arabi¯yah lil-Is?la¯h? al-Jina¯?i¯",
    "Munaz?z?amah al-Mis?ri¯yah li-H?uqu¯q al-Insa¯n",
    "Munaz?z?amat Ta¯ma¯ynu¯t",
    "Mu¯nnithi phu¯a Sukkhapha¯p Iæ Ka¯nri¯anru¯ kho¯?ng Ræ¯ngnga¯n Klum Cha¯ttiphan",
    "Namibia. Office of the Ombudsman",
    "NAMRIGHTS (Namibia)",
    "National Campaign on Dalit Human Rights (India)",
    "National Human Rights Commission (Mauritius)",
    "National Human Rights Commission (Nepal)",
    "National Protection Working Group (Nepal)",
    "National Society for Human Rights (Namibia)",
    "Network for North Korean Democracy and Human Rights",
    "Network Movement for Justice and Development",
    "Network of Concerned Historians",
    "New Zealand. Human Rights Commission",
    "Nigeria. National Human Rights Commission",
    "Northern Ireland. Human Rights Commission",
    "Office of the Ombudsman of Trinidad and Tobago",
    "Ombudsman Republike Srpske--zas?titnik ljudskih prava",
    "One Million Signatures Demanding Changes to Discriminatory Laws (Campaign)",
    "Organizacio´n Argentina de Jo´venes para las Naciones Unidas",
    "Organizat?s?ii?a? Drom",
    "Other Russia (Coalition)",
    "Pakistan International Human Rights Organization",
    "Palestinian Human Rights Monitoring Group",
    "Peace Brigades International",
    "Philippines. Commission on Human Rights",
    "Physicians for Human Rights (U.S.)",
    "Pizhva¯k-i H?uqu¯q-i Bashar dar I¯ra¯n (Organization)",
    "Point Pedro Institute of Development",
    "Pravovai?a? init?s?iativa po Rossii",
    "Privacy International (Organization)",
    "Procuraduri´a para la Defensa de los Derechos Humanos (Nicaragua)",
    "Puerto Rico. Oficina del Procurador del Ciudadano",
    "Qendra Shqiptare pe¨r te¨ Drejtat e Njeriut",
    "RADDHO (Organization)",
    "RaÌ?bitÌ£ah al-JazaÌ?Ê¾iriÌ?yah lil-DifaÌ?Ê» Ê»an HÌ£uquÌ?q al-InsaÌ?n",
    "Raoof, Ramy",
    "Re´seau des journalistes pour les droits de l'homme",
    "Re´seau national de de´fense des droits humains (Haiti)",
    "Rights Exposure Project",
    "Rwanda. National Unity and Reconciliation Commission",
    "Samba?nth Khmaer Jam?ry?an nin? Ka¯rba¯rsiddhi Manuss",
    "Sa´nchez, Yoani, 1975-",
    "Satellite Sentinel Project",
    "Sdruz?eni´ Dz?eno",
    "Shabakah al-?Arabi¯yah li-Ma?lu¯ma¯t H?uqu¯q al-Insa¯n",
    "Shirkat Gah",
    "Shomre mishpat? (Organization : Jerusalem)",
    "Sin Fronteras, I.A.P",
    "Solidarity Peace Trust",
    "South African Human Rights Commission",
    "South Africa. Truth and Reconciliation Commission",
    "Sri Lanka. Human Rights Commission",
    "Students for a Free Tibet",
    "SUARAM (Organization)",
    "Tanzania. Commission for Human Rights and Good Governance",
    "Tanzania Gender Networking Programme",
    "Tapol (Organization)",
    "Terra de Direitos (Organization)",
    "Think Centre (Singapore)",
    "TibetInfoNet (Organization)",
    "Transition Monitoring Group (Nigeria)",
    "Transparency International",
    "T?S?entr informat?s?ii¨ ta dokumentat?s?ii¨ kryms'kykh tatar",
    "Tu¨rkiye I?nsan Haklari Vakfi",
    "Uganda Coalition on the International Criminal Court",
    "Uganda Human Rights Commission",
    "UluslararasÄ± Af OÌ?rguÌ?tuÌ?--TuÌ?rkiye",
    "University Teachers for Human Rights (Jaffna)",
    "[Unknown]",
    "Unrepresented Nations and Peoples Organization",
    "Voix des sans-voix pour les droits de l'homme (Organization)",
    "Wa7da Masrya",
    "Weise, 1966-",
    "Women for Afghan Women (Organization)",
    "Women Living Under Muslim Laws (Organization)",
    "World Organisation Against Torture",
    "Ya?Ityop?ya¯ sab?awi mabtoc? guba¯?e´",
    "Ya¯tana¯pi¯d?ita Saroka¯ra Kendra (Kathmandu, Nepal)",
    "Yemeni Human Rights Network",
    "Zambia. Permanent Human Rights Commission",
    "Zimbabwe Civic Action Support Group",
    "Zimbabwe Human Rights NGO Forum",
    "Zimbabwe Lawyers for Human Rights",
  ]
  
  
  @domain_filter_options = [
    "advocacyforum.org",
    "amigosdemujeres.org",
    "amnesty.ca",
    "amnestyghana.org",
    "amnesty.hu",
    "amnesty.ie",
    "amnestymauritius.org",
    "amnestynepal.org",
    "amnesty.org.pl",
    "amnesty.org.ua",
    "amnesty.or.jp",
    "amnesty.tg",
    "amnistia.org.mx",
    "asvdh.net",
    "awid.org",
    "bgcentar.placebo.co.yu",
    "byshr.org",
    "camp.org.pk",
    "cdhrap.net",
    "centroprodh.org.mx",
    "chrr.ultinets.net",
    "codeh.hn",
    "derechoshumanos.pe",
    "drom-vidin.org",
    "dte.gn.apc.org",
    "eaaf.typepad.com",
    "ebfhr.blogspot.com",
    "ecumene.org",
    "ecwronline.org",
    "hrc-eritrea.org",
    "hrcsl.lk",
    "hrfssaudiarabia.org",
    "humanrights.dk",
    "icdcprague.org",
    "jinsil.go.kr",
    "madre.org",
    "membres.lycos.fr",
    "nwrcegypt.org",
    "ombuds.am",
    "ombudsman.gov.az",
    "openarab.net",
    "physiciansforhumanrights.org",
    "pointpedro.org",
    "raddho.org",
    "savetibet.org",
    "stopstonningnow.com",
    "studentsforafreetibet.org",
    "tamaynut.org",
    "tapol.gn.apc.org",
    "terradedireitos.org.br",
    "therightsexposureproject.com",
    "wayback.archive-it.org",
    "welcome.to",
    "woeser.middle-way.net",
    "www.518.org",
    "www.aappb.org",
    "www.abrandh.org.br",
    "www.abuelas.org.ar",
    "www.accesstojustice-ng.org",
    "www.acdauk.org.uk",
    "www.acdhrs.org",
    "www.achr.org",
    "www.achrs.org",
    "www.achrweb.org",
    "www.acri.org.il",
    "www.adc.org.ar",
    "www.afad-online.org",
    "www.afapredesa.org",
    "www.africaidp.org",
    "www.africancourtcoalition.org",
    "www.aihrc.org.af",
    "www.aldameer.org",
    "www.algeria-watch.org",
    "www.algerie-laddh.org",
    "www.alhaq.org",
    "www.amdh.org.ma",
    "www.amnesty.at",
    "www.amnesty.ch",
    "www.amnesty.cz",
    "www.amnesty.eu",
    "www.amnesty.fi",
    "www.amnesty.fo",
    "www.amnesty.fr",
    "www.amnesty.hr",
    "www.amnesty.is",
    "www.amnesty.lu",
    "www.amnesty.md",
    "www.amnesty.no",
    "www.amnesty.org",
    "www.amnesty.org.ar",
    "www.amnesty.org.gr",
    "www.amnesty.org.ph",
    "www.amnesty.org.py",
    "www.amnesty.org.tr",
    "www.amnesty.org.za",
    "www.amnesty.se",
    "www.amnesty.sk",
    "www.amnistia.cl",
    "www.amnistia-internacional.pt",
    "www.amnistia.org.pe",
    "www.amnistia.org.uy",
    "www.amnistiapr.org",
    "www.andalusitas.net",
    "www.anhri.net",
    "www.aphra.org",
    "www.aproarab.org",
    "www.apt.ch",
    "www.arabhra.org",
    "www.ardhd.org",
    "www.asiapacificforum.net",
    "www.asper-eritrea.com",
    "www.aware.org.sg",
    "www.baheyya.blogspot.com",
    "www.baobabwomen.org",
    "www.belhelcom.org",
    "www.bgcentar.org.rs",
    "www.bimkom.org",
    "www.blc-burma.org",
    "www.bo.amnesty.org",
    "www.breakthrough.tv",
    "www.btselem.org",
    "www.burmacampaign.org.uk",
    "www.cacit.org",
    "www.caldh.org",
    "www.cavr-timorleste.org",
    "www.ccdh.org.ma",
    "www.cddghana.org",
    "www.cdhr.info",
    "www.cdifdh.org.ma",
    "www.ceddert.com",
    "www.cedha.org.ar",
    "www.cejil.org",
    "www.cels.org.ar",
    "www.centrojuanmontalvo.org.do",
    "www.cepad.org.mx",
    "www.cesr.org",
    "www.cfob.org",
    "www.cgb.nl",
    "www.chipsites.com",
    "www.chragg.go.tz",
    "www.chr.gov.ph",
    "www.cidct.org.ua",
    "www.cihrs.org",
    "www.citizenshiprightsinafrica.org",
    "www.cja.org",
    "www.cladem.org",
    "www.cmdpdh.org",
    "www.cncdh.fr",
    "www.cndh.org.mx",
    "www.cndh-togo.org",
    "www.codehupy.org",
    "www.codepu.cl",
    "www.cofadeh.org",
    "www.columbia.edu",
    "www.conadeh.hn",
    "www.concernedhistorians.org",
    "www.conectas.org",
    "www.congonline.com",
    "www.cpj.org",
    "www.cridoc.net",
    "www.crisisgroup.org",
    "www.crldht.info",
    "www.crldht.org",
    "www.csdcambodia.org",
    "www.csdh.sn",
    "www.csvr.org.za",
    "www.cvict.org.np",
    "www.cwvhr.org",
    "www.darfurconsortium.org",
    "www.defensordelpueblo.gov.ec",
    "www.defensoresenlinea.com",
    "www.defensor.gov.bo",
    "www.defensoriadelpueblo.gob.pa",
    "www.defensoriadelpueblo.gov.py",
    "www.defensoria.gob.bo",
    "www.defensoria.gob.pe",
    "www.desdecuba.com",
    "www.dhperu.org",
    "www.dhr.go.cr",
    "www.ditshwanelo.org.bw",
    "www.docip.org",
    "www.do.se",
    "www.downtoearth-indonesia.org",
    "www.dpn.gob.ar",
    "www.dwatch-bd.org",
    "www.dzeno.cz",
    "www.ecpat.net",
    "www.ehrco.org",
    "www.ehrea.org",
    "www.eisa.org.za",
    "www.elsam.or.id",
    "www.en.mosharka.org",
    "www.eohr.org",
    "www.equalityhumanrights.com",
    "www.erichina.org",
    "www.errc.org",
    "www.es.amnesty.org",
    "www.fafg.org",
    "www.fasic.org",
    "www.fawe.org",
    "www.fhri.or.ug",
    "www.flamnet.info",
    "www.flamnet.net",
    "www.focusweb.org",
    "www.fohridnetwork.org",
    "www.fohrid.org.np",
    "www.forum-asia.org",
    "www.friendsoftibet.org",
    "www.frontlinedefenders.org",
    "www.gaatw.org",
    "www.gajop.org.br",
    "www.gal-soc.org",
    "www.globalwitness.org",
    "www.gov.mu",
    "www.greensborotrc.org",
    "www.gtcrp.org",
    "www.hakielimu.org",
    "www.hambastegi.org",
    "www.hamoked.org",
    "www.hcav.am",
    "www.heritiers.org",
    "www.hmlc-egy.org",
    "www.hrca.org.au",
    "www.hrcbm.org",
    "www.hrc.co.nz",
    "www.hrcm.org.mv",
    "www.hrc.org.zm",
    "www.hrcp-web.org",
    "www.hreib.com",
    "www.hrforumzim.com",
    "www.hrln.org",
    "www.humanrights.asia",
    "www.humanrightsfirst.org",
    "www.humanrights.ge",
    "www.humanrights.gov.au",
    "www.humanrights.mw",
    "www.humanrights.org.lv",
    "www.humanrights.or.tz",
    "www.ichr.ps",
    "www.icj.org",
    "www.ic-mp.org",
    "www.idasa.org.za",
    "www.ier.ma",
    "www.ifhhro.org",
    "www.iglhrc.org",
    "www.ihop.org.tr",
    "www.ihrc.org.uk",
    "www.ihrv.org",
    "www.i-indiaonline.com",
    "www.ijr.org.za",
    "www.ilhr.org",
    "www.indesomujer.org.ar",
    "www.indict.org.uk",
    "www.inredh.org",
    "www.institut-fuer-menschenrechte.de",
    "www.institutomemoria.org.ar",
    "www.ipcb.org",
    "www.irag.org.uk",
    "www.iranhrdc.org",
    "www.iraqfoundation.org",
    "www.ishr.ch",
    "www.ishr.org",
    "www.iwant2gohome.org",
    "www.iwgia.org",
    "www.jpnuk.org.uk",
    "www.jrs.net",
    "www.jrsusa.org",
    "www.jsmp.minihub.org",
    "www.justice.gov.za",
    "www.kchr.org",
    "www.khpg.org",
    "www.khrc.or.ke",
    "www.khrp.org",
    "www.kisebbsegiombudsman.hu",
    "www.knchr.org",
    "www.komnasham.go.id",
    "www.kosovakosovo.com",
    "www.kuru.co.bw",
    "www.kwrw.org",
    "www.lawandsocietytrust.org",
    "www.lawcla.org",
    "www.lchr-eg.org",
    "www.licadho-cambodia.org",
    "www.licadho.org",
    "www.ligue-iteka.africa-web.org",
    "www.malao.org",
    "www.malawihumanrightscommission.org",
    "www.mapfoundationcm.org",
    "www.mazlumder.org",
    "www.mediafound.org",
    "www.mezan.org",
    "www.mhg.ru",
    "www.minorityrights.org",
    "www.mn-nhrc.org",
    "www.mst.org.br",
    "www.naya.org.ar",
    "www.ncdhr.org.in",
    "www.nchregypt.org",
    "www.nchr.gr",
    "www.nchr.org.jo",
    "www.nhrcnepal.org",
    "www.nhrc.nic.in",
    "www.nhrc.or.th",
    "www.nigeriarights.gov.ng",
    "www.nihrc.org",
    "www.nknet.org",
    "www.nmjd.org",
    "www.nshr.org.na",
    "www.nurc.gov.rw",
    "www.oajnu.org",
    "www.ochrance.cz",
    "www.omal.info",
    "www.ombudsman.bm",
    "www.ombudsman.gov.tt",
    "www.ombudsman.hr",
    "www.ombudsman.org.na",
    "www.ombudsmanpr.com",
    "www.ombudsmen.rs.ba",
    "www.omct.org",
    "www.pazcondignidad.org",
    "www.pchrgaza.org",
    "www.pdh.org.gt",
    "www.peacebrigades.org",
    "www.phrmg.org",
    "www.pihro.org",
    "www.privacyinternational.org",
    "www.procuraduriaddhh.gob.ni",
    "www.raddho.africa-web.org",
    "www.raipon.info",
    "www.raipon.org",
    "www.rchrs.org",
    "www.responsibilitytoprotect.org",
    "www.rhr.org.il",
    "www.rjdh-niger.org",
    "www.rnddh.org",
    "www.sahrc.org.za",
    "www.satsentinel.org",
    "www.shanwomen.org",
    "www.shirkatgah.org",
    "www.sigloxxi.org",
    "www.sinfronteras.org.mx",
    "www.slcgg.org",
    "www.sokwanele.com",
    "www.solidaritypeacetrust.org",
    "www.srji.org",
    "www.suaram.net",
    "www.suhakam.org.my",
    "www.taghyeer.net",
    "www.tchrd.org",
    "www.tgnp.org",
    "www.theotherrussia.org",
    "www.thinkcentre.org",
    "www.tibetinfonet.net",
    "www.tihv.org.tr",
    "www.tmgnigeria.org",
    "www.transparency.org",
    "www.ucicc.org",
    "www.uhrc.ug",
    "www.unpo.org",
    "www.uthr.org",
    "www.vicariadelasolidaridad.cl",
    "www.volksanw.gv.at",
    "www.vsv-rdc.com",
    "www.wa7damasrya.blogspot.com",
    "www.we-change.org",
    "www.wluml.org",
    "www.womenforafghanwomen.org",
    "www.wwhr.org",
    "www.yohr.org",
    "www.zlhr.org.zw",
    "yhrn.org",
  ]
  
  @geographic_focus_filter_options = [
    "Afghanistan",
    "Africa",
    "Africa, Eastern",
    "Africa, North",
    "Africa, Southern",
    "Africa, West",
    "Albania",
    "Algeria",
    "Arab countries",
    "Arabian Peninsula",
    "Argentina",
    "Armenia (Republic)",
    "Asia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Bermuda Islands",
    "Bolivia",
    "Bosnia and Hercegovina",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burma",
    "Burundi",
    "Cambodia",
    "Caribbean Area; Caribbean Sea",
    "Chile",
    "China",
    "Congo (Democratic Republic)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Ethiopia",
    "Europe",
    "Europe, Central",
    "Europe, Eastern",
    "Faroe Islands",
    "Finland",
    "France",
    "Gaza Strip",
    "Georgia (Republic)",
    "Germany",
    "Ghana",
    "[Global focus]",
    "Great Britain",
    "Greece",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Hong Kong (China)",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Korea (North)",
    "Korea (South)",
    "Kosovo",
    "Kyrgyzstan",
    "Latin America",
    "Latvia",
    "Liberia",
    "Luxembourg",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Middle East",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Carolina",
    "Northern Ireland",
    "Norway",
    "Pacific Ocean",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Russia (Federation)",
    "Rwanda",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "South Africa",
    "Southeast Asia",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Switzerland",
    "Tanzania",
    "Thailand",
    "Tibet (China)",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United States",
    "Uruguay",
    "West Bank",
    "Western Sahara",
    "Yemen (Republic)",
    "Zambia",
    "Zimbabwe",
  ]

  @language_filter_options = [
    "Albanian",
    "Arabic",
    "Armenian",
    "Azerbaijani",
    "Belarusian",
    "Bulgarian",
    "Burmese",
    "Chinese",
    "Creoles and Pidgins, French-based (Other)",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Faroese",
    "Finnish",
    "French",
    "Georgian",
    "German",
    "Greek, Modern (1453-)",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Korean",
    "Latvian",
    "Malay",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Nyanja",
    "Persian",
    "Polish",
    "Portuguese",
    "Pushto",
    "Quechua",
    "Romani",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tamil",
    "Tetum",
    "Thai",
    "Tibetan",
    "Tumbuka",
    "Turkish",
    "Ukrainian",
  ]

  @organization_based_in_filter_options = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Argentina",
    "Armenia (Republic)",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Bermuda Islands",
    "Bolivia",
    "Bosnia and Hercegovina",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burundi",
    "California",
    "Cambodia",
    "Canada",
    "Chile",
    "China",
    "Congo (Democratic Republic)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "District of Columbia",
    "Djibouti",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "England",
    "Eritrea",
    "Ethiopia",
    "Faroe Islands",
    "Finland",
    "France",
    "Gambia",
    "Gaza Strip",
    "Georgia (Republic)",
    "Germany",
    "Ghana",
    "Greece",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Korea (South)",
    "Kosovo",
    "Kyrgyzstan",
    "Latvia",
    "Liberia",
    "Luxembourg",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Massachusetts",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New York (State)",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "No place, unknown, or undetermined",
    "North Carolina",
    "Northern Ireland",
    "Norway",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Russia (Federation)",
    "Rwanda",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sweden",
    "Switzerland",
    "Tanzania",
    "Thailand",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Vatican City",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ]

  @organization_type_filter_options = [
    "Individual site creators",
    "National human rights institutions",
    "Non-governmental organizations",
    "Other organization types",
  ]

end
