# -*- encoding : utf-8 -*-
module HRWA::OptionsSourceHardcoded
  def bib_id_filter_options
    return [
    "4191511",
    "4751601",
    "5316489",
    "5355337",
    "5421151",
    "5533057",
    "5550172",
    "5571653",
    "6952107",
    "7033263",
    "7033264",
    "7033265",
    "7033266",
    "7033267",
    "7033268",
    "7033269",
    "7033270",
    "7038247",
    "7038248",
    "7038249",
    "7038250",
    "7038252",
    "7038253",
    "7038254",
    "7038255",
    "7038257",
    "7038258",
    "7038259",
    "7038261",
    "7038262",
    "7038263",
    "7038264",
    "7038266",
    "7038267",
    "7038269",
    "7038270",
    "7038273",
    "7038274",
    "7038286",
    "7038287",
    "7038313",
    "7038315",
    "7038318",
    "7038324",
    "7038327",
    "7038329",
    "7038337",
    "7038338",
    "7038343",
    "7038349",
    "7038350",
    "7038351",
    "7038358",
    "7038360",
    "7038369",
    "7038371",
    "7038373",
    "7038374",
    "7038375",
    "7038377",
    "7038378",
    "7038379",
    "7038380",
    "7038381",
    "7038382",
    "7038383",
    "7038386",
    "7038387",
    "7038388",
    "7038393",
    "7038397",
    "7038398",
    "7038399",
    "7038400",
    "7038402",
    "7038403",
    "7038404",
    "7038405",
    "7038406",
    "7038407",
    "7038409",
    "7038410",
    "7038411",
    "7038412",
    "7038413",
    "7038417",
    "7038418",
    "7038429",
    "7038438",
    "7038439",
    "7038443",
    "7038447",
    "7038450",
    "7038451",
    "7038455",
    "7038456",
    "7038458",
    "7038459",
    "7038462",
    "7038465",
    "7038466",
    "7038467",
    "7038487",
    "7038488",
    "7038489",
    "7038491",
    "7038492",
    "7038493",
    "7038494",
    "7038496",
    "7038497",
    "7038498",
    "7038499",
    "7038500",
    "7038501",
    "7038502",
    "7038509",
    "7038518",
    "7038521",
    "7038523",
    "7038527",
    "7038532",
    "7038537",
    "7038540",
    "7038541",
    "7038542",
    "7038543",
    "7038544",
    "7038545",
    "7038546",
    "7038548",
    "7038549",
    "7038550",
    "7038565",
    "7038567",
    "7038582",
    "7038586",
    "7038594",
    "7038602",
    "7038604",
    "7038608",
    "7038617",
    "7038618",
    "7038622",
    "7038626",
    "7038632",
    "7038633",
    "7038639",
    "7038644",
    "7038648",
    "7038649",
    "7038650",
    "7038651",
    "7038652",
    "7038653",
    "7038655",
    "7038656",
    "7038657",
    "7038659",
    "7038660",
    "7038661",
    "7038662",
    "7038665",
    "7038669",
    "7038672",
    "7038673",
    "7038674",
    "7038675",
    "7038677",
    "7038678",
    "7038679",
    "7038680",
    "7038681",
    "7038683",
    "7038685",
    "7038689",
    "7038691",
    "7038693",
    "7038694",
    "7038697",
    "7038705",
    "7038710",
    "7038721",
    "7038723",
    "7038724",
    "7038737",
    "7038742",
    "7038744",
    "7038748",
    "7038755",
    "7038757",
    "7038760",
    "7038761",
    "7038762",
    "7038763",
    "7038780",
    "7038783",
    "7038786",
    "7038790",
    "7038792",
    "7038793",
    "7038797",
    "7038800",
    "7038803",
    "7038805",
    "7038807",
    "7038808",
    "7038811",
    "7038814",
    "7038815",
    "7038819",
    "7038820",
    "7410021",
    "7410095",
    "7731591",
    "7731800",
    "7731836",
    "7732061",
    "7732064",
    "7732065",
    "7732066",
    "7732067",
    "7757146",
    "7757269",
    "7771968",
    "7799772",
    "7799921",
    "7799940",
    "7800011",
    "7800014",
    "7803400",
    "7809241",
    "7813033",
    "7813804",
    "7813805",
    "7813806",
    "7813807",
    "7815173",
    "7815764",
    "7815770",
    "7819636",
    "7819664",
    "7819678",
    "7819711",
    "7820127",
    "7822594",
    "7822959",
    "7824247",
    "7832247",
    "7834145",
    "7834591",
    "7837629",
    "7839243",
    "7839371",
    "7876812",
    "7876840",
    "7885006",
    "7885012",
    "7885543",
    "7885570",
    "7886427",
    "7887220",
    "7888713",
    "7888758",
    "7890025",
    "7890675",
    "7890712",
    "7890773",
    "7900280",
    "7901541",
    "7902541",
    "7902567",
    "7904717",
    "7904970",
    "7905016",
    "7905284",
    "7905317",
    "7905623",
    "7905779",
    "7905840",
    "7923757",
    "7928882",
    "7952294",
    "7960030",
    "7971722",
    "8011158",
    "8067914",
    "8163119",
    "8179176",
    "8229614",
    "8257091",
    "8263078",
    "8281930",
    "8287713",
    "8408166",
    "8408203",
    "8408294",
    "8409019",
    "8412117",
    "8414984",
    "8415142",
    "8415331",
    "8415370",
    "8415458",
    "8438804",
    "8438858",
    "8446737",
    "8446829",
    "8446849",
    "8446886",
    "8448889",
    "8455301",
    "8455464",
    "8455680",
    "8456088",
    "8459920",
    "8460274",
    "8481136",
    "8502012",
    "8502198",
    "8513355",
    "8513367",
    "8513460",
    "8519721",
    "8519768",
    "8519817",
    "8535465",
    "8536054",
    "8539206",
    "8539218",
    "8539234",
    "8539239",
    "8539259",
    "8539378",
    "8539924",
    "8539972",
    "8540001",
    "8540054",
    "8540401",
    "8540825",
    "8540838",
    "8540895",
    "8541975",
    "8557218",
    "8585473",
    "8586003",
    "8602383",
    "8602539",
    "8602577",
    "8602843",
    "8616290",
    "8616335",
    "8616886",
    "8618396",
    "8618609",
    "8644505",
    "8703322",
    "8775601",
    "8775896",
    "8960390",
  ]
  end

  def creator_name_filter_options
    return [
    "880-01 5.18 Kinyo?m Chaedan (Korea)",
    "880-03 Markaz al-MisÌ£riÌ? li-HÌ£uquÌ?q al-MarÊ¾ah",
    "Access to Justice (Organization : Nigeria)",
    "AcÌ§aÌ?o Brasileira pela NutricÌ§aÌ?o e Direitos Humanos",
    "Adalah (Organization)",
    "Africa Internally Displaced Persons Voice (Organization)",
    "African Centre for Democracy and Human Rights Studies",
    "Agudah li-zekhuyot ezrah? be-Yis´ra?el",
    "Al-Dameer Association for Human Rights",
    "Algeria-Watch (Organization)",
    "Amigos de las Mujeres de Juarez",
    "Amnesty International. Canadian Section-English-Speaking",
    "Amnesty International Chile",
    "Amnesty International C?R",
    "Amnesty International Danmark",
    "Amnesty International France",
    "Amnesty International. F?roya deild",
    "Amnesty International-Ghana",
    "Amnesty International. Greek Section",
    "Amnesty International Hong Kong",
    "Amnesty International Hrvatske",
    "Amnesty International. IÌslandsdeild",
    "Amnesty International. International Secretariat",
    "Amnesty International. Irish Section",
    "Amnesty International Luxembourg",
    "Amnesty International MagyarorszaÌg",
    "Amnesty International. Mauritius Section",
    "Amnesty International Moldova",
    "Amnesty International Nepal",
    "Amnesty International. Nihon Shibu",
    "Amnesty International Norge",
    "Amnesty International O¨sterreich",
    "Amnesty International Pilipinas",
    "Amnesty International Polska",
    "Amnesty International. Schweizer Sektion",
    "Amnesty International. Secc¸a~o Portuguesa",
    "Amnesty International. Seccio´n Argentina",
    "Amnesty International. Seccio´n Espano~la",
    "Amnesty International. Seccio´n Paraguaya",
    "Amnesty International. Seccio´n Peruana",
    "Amnesty International. Seccio´n Uruguay",
    "Amnesty International. Section Togo",
    "Amnesty International Slovensko",
    "Amnesty International South Africa",
    "Amnesty International. Svenska sektionen",
    "Amnesty International v Ukrai¨ni",
    "Amnesty Suomessa",
    "Amnisti´a Internacional Bolivia",
    "Amnisti´a Internacional Puerto Rico",
    "AmnistiÌa Internacional MeÌxico",
    "Anti Caste Discrimination Alliance",
    "Arab Association for Human Rights (Israel)",
    "Argentina. Defensor del Pueblo de la Nacio´n",
    "Asian Centre for Human Rights",
    "Asian Federation Against Involuntary Disappearances (Philippines)",
    "Asian Forum for Human Rights and Development",
    "Asian Human Rights Commission",
    "Asia Pacific Forum of National Human Rights Institutions",
    "AsociacioÌn Paz con Dignidad",
    "Asociacio´n de Abuelas de Plaza de Mayo",
    "Asociacio´n de Familiares de Presos y Desaparecidos Saharauis",
    "Asociacio´n Paz con Dignidad",
    "Asociacio´n por los Derechos Civiles (Buenos Aires, Argentina)",
    "Assistance Association for Political Prisoners (Burma)",
    "Association for the Prevention of Torture",
    "Association for Women's Rights in Development",
    "Association of Women for Action and Research",
    "Association pour le respect des droits de l'homme aÌ? Djibouti",
    "Association sahraouie des victimes des violations graves des droits de l'homme commises par l'Etat du Maroc",
    "Associazione per la tutela dei diritti umani del popolo Eritreo",
    "Assot?s?iat?s?ii?a? korennykh malochislennykh narodov Severa, Sibiri i Dal'nego Vostoka Rossii?skoi? Federat?s?ii",
    "Australian Human Rights Commission",
    "Austria. Volksanwaltschaft",
    "Aza¨rbaycan Respublikasinin I?nsan Hu¨quqlari U¨zra¨ Mu¨va¨kkili",
    "Baheyya",
    "BAOBAB for Women's Human Rights",
    "Barna¯maj al-?Arabi¯ li-Nushat?a¯? H?uqu¯q al-Insa¯n",
    "Belaruski khel'sinski kamite?t",
    "Beogradski centar za ljudska prava",
    "Bermuda Ombudsman",
    "Be-tselem (Organization : Jerusalem)",
    "Bimkom (Organization : Jerusalem)",
    "Bod-kyi ?Gro-ba Mi?i-thob-than? dan? Man?-gtso-?phel-rgyas Lte-gnas-khan? (Dharmsa¯la, India)",
    "Breakthrough (Organization)",
    "Burma Campaign UK",
    "Burma Lawyers' Council",
    "Campaign for Good Governance",
    "Canadian Friends of Burma",
    "Catholic Church. Archdiocese of Santiago (Chile). Vicari´a de la Solidaridad. Fundacio´n Documentacio´n y Archivo",
    "Center for Democracy &amp; Human Rights in Saudi Arabia",
    "Center for Democracy and Reconciliation in Southeast Europe",
    "Center for Economic and Social Rights",
    "Center for Justice and Accountability",
    "Center for Justice and International Law",
    "Centre for Democratic Development, Research and Training",
    "Centre for Human Rights &amp; Rehabilitation (Lilongwe, Malawi)",
    "Centre for the Study of Violence and Reconciliation",
    "Centre for War Victims and Human Rights",
    "Centro de Derechos Humanos Miguel Agusti´n Pro Jua´rez",
    "Centro de Derechos Humanos y Ambiente",
    "Centro de Estudios Legales y Sociales (Argentina)",
    "Centro de Estudios Sociales Padre Juan Montalvo, SJ",
    "Centro de Justicia para la Paz y el Desarrollo",
    "Centro para la Accio´n Legal en Derechos Humanos",
    "Child Rights Information &amp; Documentation Centre",
    "Chile Information Project",
    "Chinsil, Hwahae ru?l wihan Kwago?sa Cho?ngni Wiwo?nhoe",
    "Citizenship Rights in Africa Initiative",
    "Coalition for an Effective African Court on Human and Peoples' Rights",
    "Collectif des associations contre l'impunite´ au Togo",
    "Comisio´n Mexicana de Defensa y Promocio´n de los Derechos Humanos",
    "Comissa~o de Acolhimento, Verdade, e Reconciliac?a~o Timor Leste",
    "Comite´ de Familiares de Detenidos-Desaparecidos en Honduras",
    "ComiteÌ para la Defensa de los Derechos Humanos en Honduras",
    "Comite´ pour le respect des liberte´s et des droits de l'homme en Tunisie",
    "Comite´ se´ne´galaise des droits de l'homme",
    "Commissie Gelijke Behandeling (Netherlands)",
    "Commission nationale des droits de l'homme (Togo)",
    "Committee to Protect Journalists",
    "Community Appraisal &amp; Motivation Program",
    "CONECTAS Direitos Humanos",
    "Coordinadora de Derechos Humanos del Paraguay",
    "Coordinadora Nacional de Derechos Humanos (Peru)",
    "Corporacio´n de Promocio´n y Defensa de los Derechos del Pueblo (Chile)",
    "Costa Rica. Defensori´a de los Habitantes de la Repu´blica",
    "Croatia. Puc?ki pravobranitelj",
    "Cuban Committee for Human Rights",
    "Czech Republic. Ver?ejny´ ochra´nce pra´v",
    "Da Afgha¯nista¯n da Bashar da H?uqu¯qo da Khpalva¯k Kami¯siyu¯n",
    "Darfur Consortium",
    "Defensor del Pueblo (Bolivia)",
    "Defensori´a del Pueblo de la Repu´blica de Panama´",
    "Defensori´a del Pueblo (Ecuador)",
    "Defensori´a del Pueblo (Peru)",
    "DefensoriÌa del Pueblo (Paraguay)",
    "Democracywatch (Organization : Dhaka, Bangladesh)",
    "Deutsches Institut fu¨r Menschenrechte",
    "Diskrimineringsombudsmannen (Sweden)",
    "Ditshwanelo (Organization)",
    "Down to Earth (Organization)",
    "ECPAT International",
    "EdÌ£bhokesiÌ? Phorama (Kathmandu, Nepal)",
    "Electoral Institute of Southern Africa",
    "Empowerment and Rights Institute (China)",
    "Eritrean Human Rights Electronic Archive",
    "European Roma Rights Center",
    "Focus on the Global South (Program)",
    "Forces de libe´ration africaines de Mauritanie",
    "Forum for African Women Educationalists",
    "Foundation for Human Rights Initiative",
    "France. Commission nationale consultative des droits de l'homme",
    "Friends of Tibet, INDIA",
    "Front Line (Organization)",
    "FundacioÌn de Antropologia Forense de Guatemala",
    "Fundacio´n de Ayuda Social de las Iglesias Cristianas",
    "Fundacio´n Regional de Asesori´a en Derechos Humanos",
    "Gabinete de Assessoria Juri´dica as Organizac¸oes Populares",
    "Ghana Center for Democratic Development",
    "Global Alliance against Traffic in Women",
    "Global Witness (Organization)",
    "Great Britain. Equality and Human Rights Commission",
    "Greece. Ethnike¯ Epitrope¯ gia ta Dikaio¯mata tou Anthro¯pou",
    "Greensboro Truth &amp; Community Reconciliation Project",
    "Greensboro Truth &amp; Reconciliation Commission",
    "Guatemala. Procurador de los Derechos Humanos",
    "HakiElimu (Tanzania)",
    "Hay?ah al-Mustaqillah li-H?uqu¯q al-Insa¯n (West Bank)",
    "Hayastani Hanrapetut?yan Mardu Iravunk?neri Pashtpan",
    "HayÊ¾ah al-FilastÌ£iÌ?niÌ?yah al-Mustaqillah li-HÌ£uquÌ?q al-MuwaÌ?tÌ£in",
    "Helsinki Citizens' Assembly. Vanadzor Office",
    "He´ritiers de la justice (Organization)",
    "Honduras. Comisionado Nacional de los Derechos Humanos",
    "Human Rights Centre (T?bilisi, Georgia)",
    "Human Rights Commission of Pakistan",
    "Human Rights Commission of the Maldives",
    "Human Rights Concern Eritrea (Organization)",
    "Human Rights Congress for Bangladesh Minorities",
    "Human Rights Council of Australia Inc",
    "Human Rights Education Institute of Burma",
    "Human Rights First (Organization)",
    "Human Rights First Society",
    "Human Rights Law Network (New Delhi, India)",
    "Hungary. Nemzeti e´s Etnikai Kisebbse´gi Jogok Orsza´ggyu?le´si Biztosa",
    "I-India (Organization)",
    "IÌ?nsan HaklarÄ± Ortak Platformu",
    "India. National Human Rights Commission",
    "INDICT",
    "Indigenous Peoples' Center for Documentation, Research and Information",
    "Indigenous Peoples Council on Biocolonialism",
    "Institute for Democracy in Africa",
    "Institute for Justice and Reconciliation (South Africa)",
    "Institut for menneskerettigheder (Denmark)",
    "Instituto de Estudios Juridico Sociales de la Mujer",
    "Instituto Espacio para la Memoria (Argentina)",
    "International Campaign for Tibet",
    "International Coalition for the Responsibility to Protect",
    "International Commission of Jurists (1952- )",
    "International Commission on Missing Persons",
    "International Committee Against Stoning",
    "International Committee for Democracy in Cuba",
    "International Committee of Solidarity for Political Prisoners in Tunisia",
    "International Crisis Group",
    "International Federation of Health and Human Rights Organisations",
    "International Federation of Iranian Refugees",
    "International Gay and Lesbian Human Rights Commission",
    "International League for Human Rights",
    "International Network for the Rights of Female Victims of Violence in Pakistan",
    "International Service for Human Rights",
    "International Society for Human Rights",
    "International Work Group for Indigenous Affairs",
    "Iran Human Rights Documentation Center",
    "Iraq Foundation",
    "Iraqi Human Rights Group",
    "Islamic Human Rights Commission (Great Britain)",
    "JamÊ»iÌ?yat ShabaÌ?b al-BahÌ£rayn li-HÌ£uquÌ?q al-InsaÌ?n",
    "Jam?i¯yah al-Jali¯l",
    "Jam?i¯yah al-Maghribi¯yah li-H?uqu¯q al-Insa¯n",
    "Jam?i¯yah al-Mis?ri¯yah lil-Nuhu¯d bi-al-Musha¯rakah al-Mujtama?i¯yah",
    "Jam?i¯yah al-Wat?ani¯yah lil-Taghyi¯r (Egypt)",
    "Jesuit Refugee Service",
    "Jesuit Refugee Service/USA",
    "Judicial System Monitoring Programme",
    "Jumma Peoples Network UK",
    "Kadinin I?nsan Haklari--Yeni Co¨zu¨mler",
    "Kenya Human Rights Commission",
    "Kenya National Commission on Human Rights",
    "Khana Kammaka¯n Sitthi Manutsayachon hæ¯ng Cha¯t (Thailand)",
    "Kharkivs'ka pravozakhysna hrupa",
    "Khru¯aikha¯i Patibat Nga¯n Phu¯a Sattri¯ Cha¯o Thai Yai",
    "Khu?nii? E?rkhii?n U?nde?snii? Komiss (Mongolia)",
    "Kituo cha Sheria na Haki za Binadamu (Tanzania)",
    "Komnas HAM (Indonesia)",
    "KosovaLive (Organization)",
    "Kurdish Human Rights Project",
    "Kurdish Women's Rights Watch",
    "Kuru Family of Organisations",
    "Kyrgyz Committee for Human Rights",
    "Lajnat al-Difa¯? ?an H?uqu¯q al-Insa¯n fi¯ Shibh al-Jazi¯rah al-?Arabi¯yah",
    "Land Center for Human Rights (Egypt)",
    "Latin American and Caribbean Committee for the Defense of Women's Rights",
    "Latvian Centre for Human Rights",
    "Law and Society Trust (Sri Lanka)",
    "Law in the Service of Man (Organization : Ra¯m Alla¯h)",
    "Lawyers Centre for Legal Assistance (Sierra Leone)",
    "Lembaga Studi dan Advokasi Masyarakat (Jakarta, Indonesia)",
    "Liberia. Truth and Reconciliation Commission",
    "Ligue burundaise des droits de l'homme",
    "Madre (Organization)",
    "Majhamandal samÌ£rap QbhivadhnÌ? SangamÌ£ (Phnom Penh, Cambodia)",
    "Majlis al-Istisha¯ri¯ li-H?uqu¯q al-Insa¯n (Morocco)",
    "Majlis al-Qawmi¯ li-H?uqu¯q al-Insa¯n (Egypt)",
    "Majlis al-Wat?ani¯ lil-H?urri¯ya¯t bi-Tu¯nis",
    "Malawi. Human Rights Commission",
    "Malawi Human Rights Resource Centre",
    "Malaysia. Suruhanjaya Hak Asasi Manusia Malaysia",
    "Ma¯nava Adhika¯ra tatha¯ Praja¯ta¯ntrika Man~ca (Kathmandu, Nepal)",
    "Markaz al-Filast?i¯ni¯ li-H?uqu¯q al-Insa¯n",
    "Markaz al-Mi¯za¯n li-H?uqu¯q al-Insa¯n (Gaza Strip)",
    "Markaz al-Qa¯hirah li-Dira¯sa¯t H?uqu¯q al-Insa¯n",
    "Markaz al-Tawthi¯q wa-al-I?la¯m wa-al-Takwi¯n fi¯ Maja¯l H?uqu¯q al-Insa¯n",
    "Markaz al-Wat?ani¯ li-H?uqu¯q al-Insa¯n (Jordan)",
    "Markaz ?Amma¯n li-Dira¯sa¯t H?uqu¯q al-Insa¯n",
    "Markaz Andalus li-DiraÌ?saÌ?t al-TasaÌ?muhÌ£ wa-MunaÌ?hadÌ£at al-Ê»Unf",
    "Markaz Hisha¯m Muba¯rak lil-Qa¯nu¯n",
    "Markaz Ra¯m Alla¯h li-Dira¯sa¯t H?uqu¯q al-Insa¯n",
    "Mars?ad al-Yamani¯ li-H?uqu¯q al-Insa¯n",
    "Mazlum-Der (Organization)",
    "Media Foundation for West Africa",
    "Medijski centar Beta",
    "Mexico. Comisio´n Nacional de Derechos Humanos",
    "Minority Rights Group International",
    "MokÌ£ed la-haganat ha-peratÌ£ (Jerusalem)",
    "Morocco. HayÊ¾at al-InsÌ£aÌ?f wa-al-MusÌ£aÌ?lahÌ£ah",
    "Moskovskai?a? khel'sinkskai?a? gruppa",
    "Mouvement contre les armes le´ge`res en Afrique de l'Ouest",
    "Movimento dos Trabalhadores Rurais sem Terra (Brazil)",
    "Mu?assasat al-Mar?ah al-Jadi¯dah (Egypt)",
    "Muba¯darah al-?Arabi¯yah li-Intirnit H?urr",
    "Munaz?z?amah al-?Arabi¯yah lil-Is?la¯h? al-Jina¯?i¯",
    "Munaz?z?amah al-Mis?ri¯yah li-H?uqu¯q al-Insa¯n",
    "Munaz?z?amat Ta¯ma¯ynu¯t",
    "Mu¯nnithi phu¯a Sukkhapha¯p Iæ Ka¯nri¯anru¯ kho¯?ng Ræ¯ngnga¯n Klum Cha¯ttiphan",
    "Namibia. Office of the Ombudsman",
    "NAMRIGHTS (Namibia)",
    "National Campaign on Dalit Human Rights (India)",
    "National Human Rights Commission (Mauritius)",
    "National Human Rights Commission (Nepal)",
    "National Protection Working Group (Nepal)",
    "National Society for Human Rights (Namibia)",
    "Network for North Korean Democracy and Human Rights",
    "Network Movement for Justice and Development",
    "Network of Concerned Historians",
    "New Zealand. Human Rights Commission",
    "Nigeria. National Human Rights Commission",
    "Northern Ireland. Human Rights Commission",
    "Office of the Ombudsman of Trinidad and Tobago",
    "Ombudsman Republike Srpske--zas?titnik ljudskih prava",
    "One Million Signatures Demanding Changes to Discriminatory Laws (Campaign)",
    "Organizacio´n Argentina de Jo´venes para las Naciones Unidas",
    "Organizat?s?ii?a? Drom",
    "Other Russia (Coalition)",
    "Pakistan International Human Rights Organization",
    "Palestinian Human Rights Monitoring Group",
    "Peace Brigades International",
    "Philippines. Commission on Human Rights",
    "Physicians for Human Rights (U.S.)",
    "Pizhva¯k-i H?uqu¯q-i Bashar dar I¯ra¯n (Organization)",
    "Point Pedro Institute of Development",
    "Pravovai?a? init?s?iativa po Rossii",
    "Privacy International (Organization)",
    "Procuraduri´a para la Defensa de los Derechos Humanos (Nicaragua)",
    "Puerto Rico. Oficina del Procurador del Ciudadano",
    "Qendra Shqiptare pe¨r te¨ Drejtat e Njeriut",
    "RADDHO (Organization)",
    "RaÌ?bitÌ£ah al-JazaÌ?Ê¾iriÌ?yah lil-DifaÌ?Ê» Ê»an HÌ£uquÌ?q al-InsaÌ?n",
    "Raoof, Ramy",
    "Re´seau des journalistes pour les droits de l'homme",
    "Re´seau national de de´fense des droits humains (Haiti)",
    "Rights Exposure Project",
    "Rwanda. National Unity and Reconciliation Commission",
    "Samba?nth Khmaer Jam?ry?an nin? Ka¯rba¯rsiddhi Manuss",
    "Sa´nchez, Yoani, 1975-",
    "Satellite Sentinel Project",
    "Sdruz?eni´ Dz?eno",
    "Shabakah al-?Arabi¯yah li-Ma?lu¯ma¯t H?uqu¯q al-Insa¯n",
    "Shirkat Gah",
    "Shomre mishpat? (Organization : Jerusalem)",
    "Sin Fronteras, I.A.P",
    "Solidarity Peace Trust",
    "South African Human Rights Commission",
    "South Africa. Truth and Reconciliation Commission",
    "Sri Lanka. Human Rights Commission",
    "Students for a Free Tibet",
    "SUARAM (Organization)",
    "Tanzania. Commission for Human Rights and Good Governance",
    "Tanzania Gender Networking Programme",
    "Tapol (Organization)",
    "Terra de Direitos (Organization)",
    "Think Centre (Singapore)",
    "TibetInfoNet (Organization)",
    "Transition Monitoring Group (Nigeria)",
    "Transparency International",
    "T?S?entr informat?s?ii¨ ta dokumentat?s?ii¨ kryms'kykh tatar",
    "Tu¨rkiye I?nsan Haklari Vakfi",
    "Uganda Coalition on the International Criminal Court",
    "Uganda Human Rights Commission",
    "UluslararasÄ± Af OÌ?rguÌ?tuÌ?--TuÌ?rkiye",
    "University Teachers for Human Rights (Jaffna)",
    "[Unknown]",
    "Unrepresented Nations and Peoples Organization",
    "Voix des sans-voix pour les droits de l'homme (Organization)",
    "Wa7da Masrya",
    "Weise, 1966-",
    "Women for Afghan Women (Organization)",
    "Women Living Under Muslim Laws (Organization)",
    "World Organisation Against Torture",
    "Ya?Ityop?ya¯ sab?awi mabtoc? guba¯?e´",
    "Ya¯tana¯pi¯d?ita Saroka¯ra Kendra (Kathmandu, Nepal)",
    "Yemeni Human Rights Network",
    "Zambia. Permanent Human Rights Commission",
    "Zimbabwe Civic Action Support Group",
    "Zimbabwe Human Rights NGO Forum",
    "Zimbabwe Lawyers for Human Rights",
  ]
  end  
  
  def domain_filter_options
    return [
    "advocacyforum.org",
    "amigosdemujeres.org",
    "amnesty.ca",
    "amnestyghana.org",
    "amnesty.hu",
    "amnesty.ie",
    "amnestymauritius.org",
    "amnestynepal.org",
    "amnesty.org.pl",
    "amnesty.org.ua",
    "amnesty.or.jp",
    "amnesty.tg",
    "amnistia.org.mx",
    "asvdh.net",
    "awid.org",
    "bgcentar.placebo.co.yu",
    "byshr.org",
    "camp.org.pk",
    "cdhrap.net",
    "centroprodh.org.mx",
    "chrr.ultinets.net",
    "codeh.hn",
    "derechoshumanos.pe",
    "drom-vidin.org",
    "dte.gn.apc.org",
    "eaaf.typepad.com",
    "ebfhr.blogspot.com",
    "ecumene.org",
    "ecwronline.org",
    "hrc-eritrea.org",
    "hrcsl.lk",
    "hrfssaudiarabia.org",
    "humanrights.dk",
    "icdcprague.org",
    "jinsil.go.kr",
    "madre.org",
    "membres.lycos.fr",
    "nwrcegypt.org",
    "ombuds.am",
    "ombudsman.gov.az",
    "openarab.net",
    "physiciansforhumanrights.org",
    "pointpedro.org",
    "raddho.org",
    "savetibet.org",
    "stopstonningnow.com",
    "studentsforafreetibet.org",
    "tamaynut.org",
    "tapol.gn.apc.org",
    "terradedireitos.org.br",
    "therightsexposureproject.com",
    "wayback.archive-it.org",
    "welcome.to",
    "woeser.middle-way.net",
    "www.518.org",
    "www.aappb.org",
    "www.abrandh.org.br",
    "www.abuelas.org.ar",
    "www.accesstojustice-ng.org",
    "www.acdauk.org.uk",
    "www.acdhrs.org",
    "www.achr.org",
    "www.achrs.org",
    "www.achrweb.org",
    "www.acri.org.il",
    "www.adc.org.ar",
    "www.afad-online.org",
    "www.afapredesa.org",
    "www.africaidp.org",
    "www.africancourtcoalition.org",
    "www.aihrc.org.af",
    "www.aldameer.org",
    "www.algeria-watch.org",
    "www.algerie-laddh.org",
    "www.alhaq.org",
    "www.amdh.org.ma",
    "www.amnesty.at",
    "www.amnesty.ch",
    "www.amnesty.cz",
    "www.amnesty.eu",
    "www.amnesty.fi",
    "www.amnesty.fo",
    "www.amnesty.fr",
    "www.amnesty.hr",
    "www.amnesty.is",
    "www.amnesty.lu",
    "www.amnesty.md",
    "www.amnesty.no",
    "www.amnesty.org",
    "www.amnesty.org.ar",
    "www.amnesty.org.gr",
    "www.amnesty.org.ph",
    "www.amnesty.org.py",
    "www.amnesty.org.tr",
    "www.amnesty.org.za",
    "www.amnesty.se",
    "www.amnesty.sk",
    "www.amnistia.cl",
    "www.amnistia-internacional.pt",
    "www.amnistia.org.pe",
    "www.amnistia.org.uy",
    "www.amnistiapr.org",
    "www.andalusitas.net",
    "www.anhri.net",
    "www.aphra.org",
    "www.aproarab.org",
    "www.apt.ch",
    "www.arabhra.org",
    "www.ardhd.org",
    "www.asiapacificforum.net",
    "www.asper-eritrea.com",
    "www.aware.org.sg",
    "www.baheyya.blogspot.com",
    "www.baobabwomen.org",
    "www.belhelcom.org",
    "www.bgcentar.org.rs",
    "www.bimkom.org",
    "www.blc-burma.org",
    "www.bo.amnesty.org",
    "www.breakthrough.tv",
    "www.btselem.org",
    "www.burmacampaign.org.uk",
    "www.cacit.org",
    "www.caldh.org",
    "www.cavr-timorleste.org",
    "www.ccdh.org.ma",
    "www.cddghana.org",
    "www.cdhr.info",
    "www.cdifdh.org.ma",
    "www.ceddert.com",
    "www.cedha.org.ar",
    "www.cejil.org",
    "www.cels.org.ar",
    "www.centrojuanmontalvo.org.do",
    "www.cepad.org.mx",
    "www.cesr.org",
    "www.cfob.org",
    "www.cgb.nl",
    "www.chipsites.com",
    "www.chragg.go.tz",
    "www.chr.gov.ph",
    "www.cidct.org.ua",
    "www.cihrs.org",
    "www.citizenshiprightsinafrica.org",
    "www.cja.org",
    "www.cladem.org",
    "www.cmdpdh.org",
    "www.cncdh.fr",
    "www.cndh.org.mx",
    "www.cndh-togo.org",
    "www.codehupy.org",
    "www.codepu.cl",
    "www.cofadeh.org",
    "www.columbia.edu",
    "www.conadeh.hn",
    "www.concernedhistorians.org",
    "www.conectas.org",
    "www.congonline.com",
    "www.cpj.org",
    "www.cridoc.net",
    "www.crisisgroup.org",
    "www.crldht.info",
    "www.crldht.org",
    "www.csdcambodia.org",
    "www.csdh.sn",
    "www.csvr.org.za",
    "www.cvict.org.np",
    "www.cwvhr.org",
    "www.darfurconsortium.org",
    "www.defensordelpueblo.gov.ec",
    "www.defensoresenlinea.com",
    "www.defensor.gov.bo",
    "www.defensoriadelpueblo.gob.pa",
    "www.defensoriadelpueblo.gov.py",
    "www.defensoria.gob.bo",
    "www.defensoria.gob.pe",
    "www.desdecuba.com",
    "www.dhperu.org",
    "www.dhr.go.cr",
    "www.ditshwanelo.org.bw",
    "www.docip.org",
    "www.do.se",
    "www.downtoearth-indonesia.org",
    "www.dpn.gob.ar",
    "www.dwatch-bd.org",
    "www.dzeno.cz",
    "www.ecpat.net",
    "www.ehrco.org",
    "www.ehrea.org",
    "www.eisa.org.za",
    "www.elsam.or.id",
    "www.en.mosharka.org",
    "www.eohr.org",
    "www.equalityhumanrights.com",
    "www.erichina.org",
    "www.errc.org",
    "www.es.amnesty.org",
    "www.fafg.org",
    "www.fasic.org",
    "www.fawe.org",
    "www.fhri.or.ug",
    "www.flamnet.info",
    "www.flamnet.net",
    "www.focusweb.org",
    "www.fohridnetwork.org",
    "www.fohrid.org.np",
    "www.forum-asia.org",
    "www.friendsoftibet.org",
    "www.frontlinedefenders.org",
    "www.gaatw.org",
    "www.gajop.org.br",
    "www.gal-soc.org",
    "www.globalwitness.org",
    "www.gov.mu",
    "www.greensborotrc.org",
    "www.gtcrp.org",
    "www.hakielimu.org",
    "www.hambastegi.org",
    "www.hamoked.org",
    "www.hcav.am",
    "www.heritiers.org",
    "www.hmlc-egy.org",
    "www.hrca.org.au",
    "www.hrcbm.org",
    "www.hrc.co.nz",
    "www.hrcm.org.mv",
    "www.hrc.org.zm",
    "www.hrcp-web.org",
    "www.hreib.com",
    "www.hrforumzim.com",
    "www.hrln.org",
    "www.humanrights.asia",
    "www.humanrightsfirst.org",
    "www.humanrights.ge",
    "www.humanrights.gov.au",
    "www.humanrights.mw",
    "www.humanrights.org.lv",
    "www.humanrights.or.tz",
    "www.ichr.ps",
    "www.icj.org",
    "www.ic-mp.org",
    "www.idasa.org.za",
    "www.ier.ma",
    "www.ifhhro.org",
    "www.iglhrc.org",
    "www.ihop.org.tr",
    "www.ihrc.org.uk",
    "www.ihrv.org",
    "www.i-indiaonline.com",
    "www.ijr.org.za",
    "www.ilhr.org",
    "www.indesomujer.org.ar",
    "www.indict.org.uk",
    "www.inredh.org",
    "www.institut-fuer-menschenrechte.de",
    "www.institutomemoria.org.ar",
    "www.ipcb.org",
    "www.irag.org.uk",
    "www.iranhrdc.org",
    "www.iraqfoundation.org",
    "www.ishr.ch",
    "www.ishr.org",
    "www.iwant2gohome.org",
    "www.iwgia.org",
    "www.jpnuk.org.uk",
    "www.jrs.net",
    "www.jrsusa.org",
    "www.jsmp.minihub.org",
    "www.justice.gov.za",
    "www.kchr.org",
    "www.khpg.org",
    "www.khrc.or.ke",
    "www.khrp.org",
    "www.kisebbsegiombudsman.hu",
    "www.knchr.org",
    "www.komnasham.go.id",
    "www.kosovakosovo.com",
    "www.kuru.co.bw",
    "www.kwrw.org",
    "www.lawandsocietytrust.org",
    "www.lawcla.org",
    "www.lchr-eg.org",
    "www.licadho-cambodia.org",
    "www.licadho.org",
    "www.ligue-iteka.africa-web.org",
    "www.malao.org",
    "www.malawihumanrightscommission.org",
    "www.mapfoundationcm.org",
    "www.mazlumder.org",
    "www.mediafound.org",
    "www.mezan.org",
    "www.mhg.ru",
    "www.minorityrights.org",
    "www.mn-nhrc.org",
    "www.mst.org.br",
    "www.naya.org.ar",
    "www.ncdhr.org.in",
    "www.nchregypt.org",
    "www.nchr.gr",
    "www.nchr.org.jo",
    "www.nhrcnepal.org",
    "www.nhrc.nic.in",
    "www.nhrc.or.th",
    "www.nigeriarights.gov.ng",
    "www.nihrc.org",
    "www.nknet.org",
    "www.nmjd.org",
    "www.nshr.org.na",
    "www.nurc.gov.rw",
    "www.oajnu.org",
    "www.ochrance.cz",
    "www.omal.info",
    "www.ombudsman.bm",
    "www.ombudsman.gov.tt",
    "www.ombudsman.hr",
    "www.ombudsman.org.na",
    "www.ombudsmanpr.com",
    "www.ombudsmen.rs.ba",
    "www.omct.org",
    "www.pazcondignidad.org",
    "www.pchrgaza.org",
    "www.pdh.org.gt",
    "www.peacebrigades.org",
    "www.phrmg.org",
    "www.pihro.org",
    "www.privacyinternational.org",
    "www.procuraduriaddhh.gob.ni",
    "www.raddho.africa-web.org",
    "www.raipon.info",
    "www.raipon.org",
    "www.rchrs.org",
    "www.responsibilitytoprotect.org",
    "www.rhr.org.il",
    "www.rjdh-niger.org",
    "www.rnddh.org",
    "www.sahrc.org.za",
    "www.satsentinel.org",
    "www.shanwomen.org",
    "www.shirkatgah.org",
    "www.sigloxxi.org",
    "www.sinfronteras.org.mx",
    "www.slcgg.org",
    "www.sokwanele.com",
    "www.solidaritypeacetrust.org",
    "www.srji.org",
    "www.suaram.net",
    "www.suhakam.org.my",
    "www.taghyeer.net",
    "www.tchrd.org",
    "www.tgnp.org",
    "www.theotherrussia.org",
    "www.thinkcentre.org",
    "www.tibetinfonet.net",
    "www.tihv.org.tr",
    "www.tmgnigeria.org",
    "www.transparency.org",
    "www.ucicc.org",
    "www.uhrc.ug",
    "www.unpo.org",
    "www.uthr.org",
    "www.vicariadelasolidaridad.cl",
    "www.volksanw.gv.at",
    "www.vsv-rdc.com",
    "www.wa7damasrya.blogspot.com",
    "www.we-change.org",
    "www.wluml.org",
    "www.womenforafghanwomen.org",
    "www.wwhr.org",
    "www.yohr.org",
    "www.zlhr.org.zw",
    "yhrn.org",
  ]
  end
  
  def geographic_focus_filter_options
    return [
    "Afghanistan",
    "Africa",
    "Africa, Eastern",
    "Africa, North",
    "Africa, Southern",
    "Africa, West",
    "Albania",
    "Algeria",
    "Arab countries",
    "Arabian Peninsula",
    "Argentina",
    "Armenia (Republic)",
    "Asia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Bermuda Islands",
    "Bolivia",
    "Bosnia and Hercegovina",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burma",
    "Burundi",
    "Cambodia",
    "Caribbean Area; Caribbean Sea",
    "Chile",
    "China",
    "Congo (Democratic Republic)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Ethiopia",
    "Europe",
    "Europe, Central",
    "Europe, Eastern",
    "Faroe Islands",
    "Finland",
    "France",
    "Gaza Strip",
    "Georgia (Republic)",
    "Germany",
    "Ghana",
    "[Global focus]",
    "Great Britain",
    "Greece",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Hong Kong (China)",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Korea (North)",
    "Korea (South)",
    "Kosovo",
    "Kyrgyzstan",
    "Latin America",
    "Latvia",
    "Liberia",
    "Luxembourg",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Middle East",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Carolina",
    "Northern Ireland",
    "Norway",
    "Pacific Ocean",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Russia (Federation)",
    "Rwanda",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "South Africa",
    "Southeast Asia",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Switzerland",
    "Tanzania",
    "Thailand",
    "Tibet (China)",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United States",
    "Uruguay",
    "West Bank",
    "Western Sahara",
    "Yemen (Republic)",
    "Zambia",
    "Zimbabwe",
  ]
  end

  def language_filter_options
    return [
    "Albanian",
    "Arabic",
    "Armenian",
    "Azerbaijani",
    "Belarusian",
    "Bulgarian",
    "Burmese",
    "Chinese",
    "Creoles and Pidgins, French-based (Other)",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Faroese",
    "Finnish",
    "French",
    "Georgian",
    "German",
    "Greek, Modern (1453-)",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Korean",
    "Latvian",
    "Malay",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Nyanja",
    "Persian",
    "Polish",
    "Portuguese",
    "Pushto",
    "Quechua",
    "Romani",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tamil",
    "Tetum",
    "Thai",
    "Tibetan",
    "Tumbuka",
    "Turkish",
    "Ukrainian",
  ]
  end

  def organization_based_in_filter_options
    return [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Argentina",
    "Armenia (Republic)",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Bermuda Islands",
    "Bolivia",
    "Bosnia and Hercegovina",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burundi",
    "California",
    "Cambodia",
    "Canada",
    "Chile",
    "China",
    "Congo (Democratic Republic)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "District of Columbia",
    "Djibouti",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "England",
    "Eritrea",
    "Ethiopia",
    "Faroe Islands",
    "Finland",
    "France",
    "Gambia",
    "Gaza Strip",
    "Georgia (Republic)",
    "Germany",
    "Ghana",
    "Greece",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Korea (South)",
    "Kosovo",
    "Kyrgyzstan",
    "Latvia",
    "Liberia",
    "Luxembourg",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Massachusetts",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New York (State)",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "No place, unknown, or undetermined",
    "North Carolina",
    "Northern Ireland",
    "Norway",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Russia (Federation)",
    "Rwanda",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sweden",
    "Switzerland",
    "Tanzania",
    "Thailand",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Vatican City",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ]
  end

  def organization_type_filter_options
    return [
    "Individual site creators",
    "National human rights institutions",
    "Non-governmental organizations",
    "Other organization types",
  ]
  end
  
  def original_urls_filter_options
    return [
      "http://acda.co/",
      "http://advocacyforum.org/",
      "http://against-torture.net/",
      "http://amigosdemujeres.org/",
      "http://amnesty.ca/",
      "http://amnesty.de/",
      "http://amnesty.hu/",
      "http://amnesty.ie/",
      "http://amnesty.or.jp/",
      "http://amnesty.org.pl/",
      "http://amnesty.org.ua/",
      "http://amnesty.sn/",
      "http://amnesty.tg/",
      "http://amnesty.tw/",
      "http://amnestyghana.org/",
      "http://amnestymauritius.org/",
      "http://amnestynepal.org/",
      "http://amnistia.org.mx/",
      "http://andnettoronto.blogspot.com/",
      "http://asvdh.net/",
      "http://awid.org/",
      "http://bgcentar.placebo.co.yu/home_sr",
      "http://blog.rwhr.org/",
      "http://byshr.org/",
      "http://camp.org.pk/",
      "http://cdhrap.net/",
      "http://centroprodh.org.mx/",
      "http://chrr.ultinets.net/",
      "http://codeh.hn/v1/",
      "http://derechoshumanos.pe/",
      "http://drom-vidin.org/",
      "http://dte.gn.apc.org/",
      "http://eaaf.typepad.com/",
      "http://ebfhr.blogspot.com/",
      "http://ecumene.org/INRFVVP/",
      "http://ecwronline.org",
      "http://harakamasria.org/",
      "http://hoodonline.org/",
      "http://hrc-eritrea.org/",
      "http://hrcsl.lk/",
      "http://hrfssaudiarabia.org/",
      "http://humanrights.dk/",
      "http://humanrights.ee/",
      "http://icdcprague.org/",
      "http://ilsa.org.co:81/",
      "http://indignacion.org.mx/",
      "http://jinsil.go.kr/",
      "http://madre.org/",
      "http://membres.lycos.fr/polprisoners/icsppten.htm",
      "http://misrdigital.blogspirit.com/",
      "http://nchro.org/",
      "http://notonourwatchproject.org/",
      "http://nwrcegypt.org/",
      "http://ombuds.am/main/",
      "http://ombudsman.gov.az/",
      "http://openarab.net/en/",
      "http://persian2english.com/",
      "http://physiciansforhumanrights.org/",
      "http://pointpedro.org/",
      "http://raddho.org/",
      "http://savetibet.org/",
      "http://spring96.org/",
      "http://stopstonningnow.com/",
      "http://studentsforafreetibet.org/index.php",
      "http://tamaynut.org/",
      "http://tapol.gn.apc.org/",
      "http://terradedireitos.org.br/",
      "http://therightsexposureproject.com/",
      "http://unictr.org",
      "http://volksanwaltschaft.gv.at/",
      "http://woeser.middle-way.net/",
      "http://worecnepal.org/",
      "http://www.518.org/",
      "http://www.aappb.org/",
      "http://www.abrandh.org.br/",
      "http://www.abuelas.org.ar/",
      "http://www.accesstojustice-ng.org/",
      "http://www.acdauk.org.uk/",
      "http://www.acdhrs.org/",
      "http://www.achpr.org/",
      "http://www.achr.org/en/index.html",
      "http://www.achrs.org/",
      "http://www.achrweb.org/index.htm",
      "http://www.acri.org.il/",
      "http://www.acrr.ro/",
      "http://www.adalah.org/eng/index.php",
      "http://www.adc.org.ar/",
      "http://www.afad-online.org/",
      "http://www.afapredesa.org/index.php",
      "http://www.africaidp.org/",
      "http://www.africancourtcoalition.org/",
      "http://www.aihrc.org.af/",
      "http://www.ajpdangola.org/",
      "http://www.aldameer.org/ar/index.php",
      "http://www.algeria-watch.org/index_en.htm",
      "http://www.algerie-laddh.org/",
      "http://www.alhaq.org/",
      "http://www.alrc.net/index.php",
      "http://www.amdh.org.ma/",
      "http://www.amnesty.at/",
      "http://www.amnesty.be",
      "http://www.amnesty.ch/de",
      "http://www.amnesty.cz/",
      "http://www.amnesty.dk/",
      "http://www.amnesty.eu/",
      "http://www.amnesty.fi",
      "http://www.amnesty.fo/",
      "http://www.amnesty.fr/",
      "http://www.amnesty.hr",
      "http://www.amnesty.is/",
      "http://www.amnesty.it",
      "http://www.amnesty.lu/",
      "http://www.amnesty.md/",
      "http://www.amnesty.nl/",
      "http://www.amnesty.no/",
      "http://www.amnesty.org",
      "http://www.amnesty.org.ar/",
      "http://www.amnesty.org.au/",
      "http://www.amnesty.org.gr/",
      "http://www.amnesty.org.hk/",
      "http://www.amnesty.org.nz/",
      "http://www.amnesty.org.ph/",
      "http://www.amnesty.org.py/",
      "http://www.amnesty.org.tr/",
      "http://www.amnesty.org.uk/",
      "http://www.amnesty.org.za/",
      "http://www.amnesty.se/",
      "http://www.amnesty.sk/",
      "http://www.amnistia-internacional.pt/",
      "http://www.amnistia.cl/web/",
      "http://www.amnistia.org.pe/",
      "http://www.amnistia.org.uy/",
      "http://www.amnistiapr.org/",
      "http://www.andalusitas.net/",
      "http://www.andhes.org.ar/",
      "http://www.anhri.net/",
      "http://www.aphra.org/",
      "http://www.aproarab.org/",
      "http://www.aprodeh.org.pe/",
      "http://www.apt.ch/",
      "http://www.arabhra.org/",
      "http://www.ardhd.org/",
      "http://www.article19.org/",
      "http://www.asiapacificforum.net/",
      "http://www.asper-eritrea.com/",
      "http://www.aware.org.sg/",
      "http://www.azhumanrights.az/",
      "http://www.baheyya.blogspot.com/",
      "http://www.ban.org/",
      "http://www.baobabwomen.org/",
      "http://www.belhelcom.org/",
      "http://www.bgcentar.org.rs/",
      "http://www.bimkom.org/",
      "http://www.birw.org/",
      "http://www.blc-burma.org/",
      "http://www.bo.amnesty.org/",
      "http://www.breakthrough.tv/",
      "http://www.btselem.org/English/index.asp",
      "http://www.burmacampaign.org.uk/",
      "http://www.cacit.org/",
      "http://www.cageprisoners.com/",
      "http://www.cajpe.org.pe/index.html",
      "http://www.caldh.org/",
      "http://www.cavr-timorleste.org/",
      "http://www.ccdh.org.ma/",
      "http://www.cddghana.org/",
      "http://www.cdhr.info/",
      "http://www.cdifdh.org.ma/",
      "http://www.ceddert.com/",
      "http://www.cedepmalawi.org/",
      "http://www.cedha.org.ar/",
      "http://www.cejil.org/",
      "http://www.cels.org.ar",
      "http://www.cenidh.org/",
      "http://www.centrojuanmontalvo.org.do/",
      "http://www.cepad.org.mx",
      "http://www.cesr.org/",
      "http://www.cfob.org/",
      "http://www.cgb.nl/",
      "http://www.child-soldiers.org/",
      "http://www.chipsites.com/derechos/index_eng.html",
      "http://www.chr.gov.ph/",
      "http://www.chragg.go.tz/",
      "http://www.cidct.org.ua/en/",
      "http://www.cihrs.org/english/default.aspx",
      "http://www.cimi.org.br/",
      "http://www.citizenshiprightsinafrica.org/",
      "http://www.cja.org/",
      "http://www.cladem.org/",
      "http://www.cmdpdh.org/",
      "http://www.cncdh.fr/",
      "http://www.cndh-togo.org/",
      "http://www.cndh.org.mx/",
      "http://www.codehupy.org/",
      "http://www.codepu.cl/index.php",
      "http://www.cofadeh.org/",
      "http://www.colectivodeabogados.org/",
      "http://www.columbia.edu/cgi-bin/cul/resolve?clio8281930",
      "http://www.conadeh.hn/",
      "http://www.concernedhistorians.org/",
      "http://www.conectas.org/",
      "http://www.congonline.com/vsv/",
      "http://www.controlarms.org",
      "http://www.cpj.org/",
      "http://www.cridoc.net/",
      "http://www.crisisgroup.org/",
      "http://www.crldht.info",
      "http://www.crldht.org",
      "http://www.csdcambodia.org/",
      "http://www.csdh.sn/",
      "http://www.csvr.org.za/",
      "http://www.cverdad.org.pe/",
      "http://www.cvict.org.np/",
      "http://www.cwvhr.org/",
      "http://www.darfurconsortium.org/",
      "http://www.defensor.gov.bo/",
      "http://www.defensordelpueblo.gov.ec/",
      "http://www.defensoresenlinea.com/cms/",
      "http://www.defensoria.gob.bo/",
      "http://www.defensoria.gob.pe/",
      "http://www.defensoriadelpueblo.gob.pa/",
      "http://www.defensoriadelpueblo.gov.py/",
      "http://www.derechos.org.ve/",
      "http://www.desdecuba.com/generaciony/",
      "http://www.dhperu.org/",
      "http://www.dhr.go.cr/",
      "http://www.ditshwanelo.org.bw/",
      "http://www.do.se/",
      "http://www.docip.org/",
      "http://www.downtoearth-indonesia.org/",
      "http://www.dpe.gob.ec/",
      "http://www.dpn.gob.ar/",
      "http://www.dwatch-bd.org/index.html",
      "http://www.dzeno.cz/",
      "http://www.ecpat.net/",
      "http://www.ehrco.org/",
      "http://www.ehrea.org/",
      "http://www.eisa.org.za/",
      "http://www.elsam.or.id/new/index.php",
      "http://www.en.afteegypt.org",
      "http://www.en.mosharka.org/",
      "http://www.eohr.org/",
      "http://www.equalityhumanrights.com/",
      "http://www.equalrightstrust.org/",
      "http://www.erichina.org/english/englishhome.htm",
      "http://www.errc.org/",
      "http://www.es.amnesty.org/",
      "http://www.fafg.org",
      "http://www.famafrique.org/",
      "http://www.fasic.org/",
      "http://www.fawe.org/",
      "http://www.fhri.or.ug/",
      "http://www.flamnet.info/",
      "http://www.flamnet.net/",
      "http://www.focusweb.org",
      "http://www.fohrid.org.np/",
      "http://www.fohridnetwork.org/",
      "http://www.forum-asia.org/",
      "http://www.friendsoftibet.org/",
      "http://www.frontlinedefenders.org/",
      "http://www.gaatw.org/",
      "http://www.gajop.org.br/",
      "http://www.gal-soc.org/",
      "http://www.gdf.ru/",
      "http://www.global.org.br/",
      "http://www.globalwitness.org/",
      "http://www.gov.mu/portal/site/nhrcsite",
      "http://www.greensborotrc.org/",
      "http://www.gtcrp.org/",
      "http://www.hakielimu.org/",
      "http://www.hambastegi.org/",
      "http://www.hamoked.org/",
      "http://www.hcav.am/",
      "http://www.helsinki.org.rs/",
      "http://www.heritiers.org/",
      "http://www.hic-net.org/",
      "http://www.hlc-rdc.org/",
      "http://www.hmlc-egy.org/",
      "http://www.hra.am/",
      "http://www.hrc.co.nz/",
      "http://www.hrc.org.zm/",
      "http://www.hrca.org.au/",
      "http://www.hrcbm.org/",
      "http://www.hrcm.org.mv/",
      "http://www.hrcp-web.org/",
      "http://www.hreib.com/",
      "http://www.hrforumzim.com/",
      "http://www.hrln.org/hrln/",
      "http://www.humanrights.asia/",
      "http://www.humanrights.ge/",
      "http://www.humanrights.go.kr/english/index.jsp",
      "http://www.humanrights.gov.au/",
      "http://www.humanrights.mw/",
      "http://www.humanrights.or.tz/",
      "http://www.humanrights.org.lv/html/",
      "http://www.humanrightsfirst.org/",
      "http://www.humanrightspoint.si/",
      "http://www.hurryat.org/",
      "http://www.i-indiaonline.com/",
      "http://www.ic-mp.org/",
      "http://www.iccwomen.org/",
      "http://www.ichr.ps/",
      "http://www.icj.org/",
      "http://www.idasa.org.za/",
      "http://www.idasa.org/",
      "http://www.idl.org.pe/",
      "http://www.ier.ma/",
      "http://www.ifhhro.org/",
      "http://www.iglhrc.org/",
      "http://www.ihop.org.tr/",
      "http://www.ihrc.org.uk/",
      "http://www.ihrv.org/",
      "http://www.ijr.org.za/",
      "http://www.ilhr.org/index.html",
      "http://www.indesomujer.org.ar/",
      "http://www.indict.org.uk/index.php",
      "http://www.inredh.org/",
      "http://www.institut-fuer-menschenrechte.de/",
      "http://www.institutomemoria.org.ar/index.html",
      "http://www.ipcb.org/",
      "http://www.irag.org.uk/eindex.php",
      "http://www.iranhrdc.org/httpdocs/index.htm",
      "http://www.iraqfoundation.org/",
      "http://www.ishr.ch/",
      "http://www.ishr.org/",
      "http://www.iwant2gohome.org",
      "http://www.iwgia.org/",
      "http://www.jpnuk.org.uk/",
      "http://www.jrs.net/",
      "http://www.jrsusa.org/",
      "http://www.jsmp.minihub.org/",
      "http://www.justice.gov.za/trc/",
      "http://www.kchr.org/",
      "http://www.khpg.org/",
      "http://www.khrc.or.ke/",
      "http://www.khrp.org/",
      "http://www.kisebbsegiombudsman.hu/",
      "http://www.knchr.org/",
      "http://www.komnasham.go.id/",
      "http://www.kosovakosovo.com/",
      "http://www.kuru.co.bw/",
      "http://www.kwrw.org/",
      "http://www.lawandsocietytrust.org/",
      "http://www.lawandsocietytrust.org/web/",
      "http://www.lawcla.org/",
      "http://www.lchr-eg.org/",
      "http://www.licadho-cambodia.org/",
      "http://www.licadho.org/",
      "http://www.ligue-iteka.africa-web.org/index.php3",
      "http://www.malao.org/",
      "http://www.malawihumanrightscommission.org/",
      "http://www.mapfoundationcm.org/",
      "http://www.mazlumder.org/",
      "http://www.mediafound.org/",
      "http://www.memoriaabierta.org.ar/",
      "http://www.mezan.org/",
      "http://www.mhg.ru/",
      "http://www.minorityrights.org/",
      "http://www.mn-nhrc.org/",
      "http://www.mndh.org.br/",
      "http://www.mst.org.br/",
      "http://www.naya.org.ar/eaaf/",
      "http://www.ncciraq.org/",
      "http://www.ncdhr.org.in/",
      "http://www.nchr.gr/",
      "http://www.nchr.org.jo/",
      "http://www.nchregypt.org/",
      "http://www.newtactics.org/",
      "http://www.nhrc-qa.org/",
      "http://www.nhrc.nic.in/",
      "http://www.nhrc.or.th/",
      "http://www.nhrcnepal.org/",
      "http://www.nigeriarights.gov.ng/",
      "http://www.nihrc.org/",
      "http://www.nknet.org/",
      "http://www.nmjd.org/",
      "http://www.nshr.org.na/",
      "http://www.nubasurvival.com/",
      "http://www.nurc.gov.rw/",
      "http://www.oajnu.org/",
      "http://www.observatorio.cl/",
      "http://www.ochrance.cz/",
      "http://www.omal.info/www/sommaire.php3",
      "http://www.ombudsman.bm",
      "http://www.ombudsman.gov.tt/",
      "http://www.ombudsman.hr/",
      "http://www.ombudsman.mk/",
      "http://www.ombudsman.org.na/",
      "http://www.ombudsmanpr.com/",
      "http://www.ombudsmen.rs.ba/",
      "http://www.omct.org/",
      "http://www.omdh.org/",
      "http://www.pazcondignidad.org/",
      "http://www.pchrgaza.org/",
      "http://www.pdh.org.gt/",
      "http://www.peacebrigades.org/",
      "http://www.phrmg.org/",
      "http://www.pidhdd.org/",
      "http://www.pihro.org/",
      "http://www.privacyinternational.org/",
      "http://www.procuraduriaddhh.gob.ni/",
      "http://www.raddho.africa-web.org/",
      "http://www.raipon.info/",
      "http://www.raipon.org/",
      "http://www.rchrs.org/",
      "http://www.rdc-viol.org/",
      "http://www.responsibilitytoprotect.org/",
      "http://www.rhr.org.il/",
      "http://www.rjdh-niger.org/",
      "http://www.rnddh.org/index.php3",
      "http://www.safhr.org/",
      "http://www.sahrc.org.za/",
      "http://www.satsentinel.org/",
      "http://www.shanwomen.org/",
      "http://www.shirkatgah.org/",
      "http://www.sigloxxi.org/",
      "http://www.sinfronteras.org.mx/",
      "http://www.slcgg.org/",
      "http://www.social.org.br/",
      "http://www.sokwanele.com/",
      "http://www.solidaritypeacetrust.org/",
      "http://www.sova-center.ru/",
      "http://www.srebrenica.ba/",
      "http://www.srji.org/",
      "http://www.suaram.net/",
      "http://www.suhakam.org.my/",
      "http://www.survivorcorps.org/",
      "http://www.taghyeer.net/",
      "http://www.tchrd.org/",
      "http://www.tgnp.org/",
      "http://www.theadvocatesforhumanrights.org/",
      "http://www.theotherrussia.org/",
      "http://www.thinkcentre.org/",
      "http://www.tibetinfonet.net/",
      "http://www.tihv.org.tr/",
      "http://www.tjrckenya.org/",
      "http://www.tmgnigeria.org/",
      "http://www.transparency.org/",
      "http://www.ucicc.org/",
      "http://www.uhrc.ug/",
      "http://www.unpo.org/",
      "http://www.uthr.org/index.html",
      "http://www.vicariadelasolidaridad.cl/",
      "http://www.volksanw.gv.at/",
      "http://www.vsv-rdc.com/",
      "http://www.wa7damasrya.blogspot.com/",
      "http://www.we-change.org/",
      "http://www.wluml.org/english/index.shtml",
      "http://www.womenforafghanwomen.org/",
      "http://www.womenpress.net/",
      "http://www.womensnetwork.org/",
      "http://www.wwhr.org/",
      "http://www.yesh-din.org/",
      "http://www.yohr.org",
      "http://www.yucom.org.rs/",
      "http://www.zlhr.org.zw/",
      "http://yhrn.org/",

    ]
  end
  
  def subject_filter_options
    return [
      "AIDS (Disease)",
      "Adultery (Islamic law)",
      "African Americans -- Civil rights",
      "African diaspora",
      "Africans -- Civil rights.",
      "Agricultural laborers",
      "Agricultural laborers -- Social conditions.",
      "Agriculture and state",
      "Anti-globalization movement",
      "Apartheid",
      "Arab-Israeli conflict",
      "Arms transfers -- Prevention.",
      "Atrocities",
      "Berbers",
      "Bodyguards",
      "Burmese",
      "Capital punishment",
      "Caste",
      "Caste-based discrimination",
      "Censorship",
      "Chechens",
      "Child pornography -- Prevention.",
      "Child prostitution -- Prevention.",
      "Child sexual abuse -- Prevention.",
      "Child soldiers",
      "Child welfare",
      "Children",
      "Children -- Legal status, laws, etc.",
      "Children -- Services for",
      "Children and war",
      "Children's rights",
      "Church and state",
      "Church work with refugees",
      "Citizenship",
      "Civil rights",
      "Civil rights demonstrations",
      "Civil rights movements",
      "Civil rights workers -- Protection.",
      "Civil society",
      "Community development",
      "Computers -- Recycling",
      "Conflict management",
      "Conservation of natural resources",
      "Corporations -- Corrupt practices.",
      "Corruption",
      "Crimean Tatars -- Civil rights.",
      "Crimean Tatars -- Relocation.",
      "Crimes against humanity",
      "Crises",
      "Dalits",
      "Democracy",
      "Democratization",
      "Detention of persons",
      "Disappeared persons",
      "Disaster victims",
      "Discrimination",
      "Discrimination -- Law and legislation.",
      "Discrimination against Romanies",
      "Due process of law",
      "East Indians",
      "Economic development",
      "Education",
      "Elections",
      "Electronics -- Materials",
      "Energy crops -- Environmental aspects",
      "Environmental justice",
      "Environmental protection",
      "Eritrean-Ethiopian War, 1998-",
      "Eritreans -- Ethnic identity.",
      "Ethiopians -- Ethnic identity.",
      "Ethnic relations",
      "Exiles",
      "Farmers -- Social conditions.",
      "Food sovereignty",
      "Forced migration",
      "Foreign workers",
      "Forensic anthropology",
      "Free speech",
      "Freedom of association",
      "Freedom of expression",
      "Freedom of information",
      "Freedom of movement",
      "Freedom of speech",
      "Freedom of the press",
      "Gay rights",
      "Genetics and society",
      "Genocide",
      "Glasnost",
      "Globalization",
      "Government and the press",
      "Government, Resistance to",
      "Governmental investigations",
      "Gun control",
      "Gun control -- International cooperation.",
      "Hate crimes",
      "Hazardous wastes -- Environmental aspects.",
      "Health -- Social aspects.",
      "Historians -- Political activity.",
      "Honor killings",
      "Housing",
      "Human rights",
      "Human rights -- Environmental aspects",
      "Human rights -- Government policy.",
      "Human rights -- Health aspects.",
      "Human rights -- History",
      "Human rights -- Press coverage",
      "Human rights -- Press coverage.",
      "Human rights -- Religious aspects",
      "Human rights -- Research",
      "Human rights -- Study and teaching",
      "Human rights advocacy",
      "Human rights and globalization",
      "Human rights in mass media",
      "Human rights monitoring",
      "Human rights movements",
      "Human rights workers",
      "Human rights workers -- Protection.",
      "Human rights workers -- Services for.",
      "Human trafficking",
      "Humanitarian assistance",
      "Humanitarian law",
      "Immigrants",
      "Impunity",
      "Indians of South America",
      "Indians, Treatment of",
      "Indigenous peoples",
      "Indigenous peoples -- Civil rights",
      "Information policy",
      "Intellectual freedom",
      "Internally displaced persons",
      "International business enterprises",
      "International cooperation",
      "International cooperation -- Societies, etc.",
      "International criminal courts",
      "International relations -- Study and teaching",
      "Internet",
      "Internet -- Political aspects",
      "Islam and politics",
      "Islamic law",
      "Journalists -- Crimes against.",
      "Jumma (Bangladeshi people) -- Crimes against",
      "Justice, Administration of",
      "Kurdish diaspora",
      "Kurds",
      "Kwangju Uprising, Kwangju-si, Korea, 1980",
      "Land mine victims",
      "Land reform",
      "Land tenure",
      "Land use, Rural -- Social aspects",
      "Law",
      "Legal aid",
      "Legal assistance to the poor",
      "Mass media policy",
      "Mayas",
      "Medical care -- Law and legislation.",
      "Military courts",
      "Minorities",
      "Minorities -- Crimes against",
      "Missing persons",
      "Murder victims",
      "Muslim women -- Legal status, laws, etc.",
      "Nation-building",
      "National human rights institutions",
      "Nationalism",
      "Nazis",
      "Non-governmental organizations",
      "Nonprofit organizations",
      "Nuba (African people)",
      "Nutrition",
      "Ombudspersons",
      "Palestinian Arabs",
      "Palestinian Arabs -- Civil rights",
      "Palestinian Arabs -- Legal status, laws, etc.",
      "Passive resistance",
      "Peace -- Research",
      "Peace building",
      "Peace-building",
      "Peasants",
      "Persons -- Violence against",
      "Physicians -- Societies, etc.",
      "Police brutality",
      "Political activists -- Protection.",
      "Political atrocities",
      "Political corruption",
      "Political persecution",
      "Political prisoners",
      "Political prisoners -- Abuse of",
      "Political refugees",
      "Political rights",
      "Political violence -- History",
      "Political violence -- Prevention.",
      "Poverty",
      "Presidents -- Election.",
      "Prisoners",
      "Prisoners -- Civil rights",
      "Prisoners -- Legal status, laws, etc.",
      "Prisoners of war -- Legal status, laws, etc.",
      "Prisons",
      "Privacy, Right of",
      "Public interest law",
      "Race discrimination",
      "Racism",
      "Reconciliation",
      "Reconciliation -- Political aspects",
      "Refugees",
      "Refugees -- Legal status, laws, etc.",
      "Repatriation",
      "Reproductive rights",
      "Restorative justice",
      "Right to food",
      "Right to health",
      "Right to housing",
      "Romanies",
      "Romanies -- Civil rights",
      "Rule of law",
      "Rural poor",
      "Sahrawi (African people)",
      "San (African people)",
      "Sex discrimination against women",
      "Shan (Asian people)",
      "Slavery",
      "Social change",
      "Social justice",
      "Social responsibility of business",
      "Sociological jurisprudence",
      "State-sponsored terrorism",
      "Statelessness",
      "Stoning",
      "Stoning (Islamic law)",
      "Street children",
      "Sustainable development",
      "Tamil (Indic people)",
      "Torture",
      "Torture (International law)",
      "Torture -- Government policy",
      "Torture -- Prevention.",
      "Torture victims",
      "Torture victims -- Rehabilitation",
      "Transgender people",
      "Transitional justice",
      "Transparency in government",
      "Trials",
      "Trials (Crimes against humanity)",
      "Trials (Genocide)",
      "Tribes -- Civil rights",
      "Truth commissions",
      "Truth commissions -- History.",
      "Violence -- Prevention.",
      "War crimes",
      "War victims",
      "Women",
      "Women (Islamic law)",
      "Women -- Crimes against",
      "Women -- Crimes against.",
      "Women -- Education",
      "Women -- Legal status, laws, etc.",
      "Women -- Political activity",
      "Women -- Social conditions",
      "Women -- Violence against",
      "Women in Islam",
      "Women in development",
      "Women in economic development",
      "Women in sustainable development",
      "Women's rights",
      "Women, Kurdish",
      "World politics",
      "Yemeni Human Rights Network",
      "Youth",
      "Youth -- Political activity",
      "Youth movements",
      "Yugoslav War, 1991-1995 -- Atrocities",
    ]
  end

  def title_filter_options
    return [
      '5·18 Kinyŏm Chaedan : The May 18 Memorial Foundation.',
      'Abuelas de Plaza de Mayo',
      'Ação Brasileira pela Nutrição e Direitos Humanos',
      'Access to Justice',
      'Adalah',
      'Advocacy Forum--Nepal',
      'AFAPREDESA',
      'Afghanistan Independent Human Rights Commission',
      'Africa Internally Displaced Persons Voice',
      'African Centre for Democracy and Human Rights Studies',
      'African Commission on Human and Peoples\' Rights : Commission africaine des droits de l\'homme et des peuples',
      'Albanian Center for Human Rights',
      'Al-Dameer Association for Human Rights',
      'Algeria-Watch',
      'Al-Haq',
      'Alianța Civică a Romilor din Romania',
      'Al-Jamʻīyah al-Waṭanīyah lil-Taghyīr',
      'al-Majlis al-Istishārī li-Ḥuqūq al-Insān : [mawqiʻ intirnit] muʾassasat waṭanīyah lil-nuhūṣ biḥuqūq al-insān wa-ḥimāyatihā = Conseil consultatif des droits de lʹhomme : [site Web] institution nationale pour la protection des driots de lʹhomme.',
      'al-Markaz al-Miṣrī li-Ḥuqūq al-Marʾah : [mawqiʻ intirnit].',
      'al-Marṣad al-Yamanī li-Ḥuqūq al-Insān',
      'al-Waʻy al-Miṣrī',
      'Amigos de las Mujeres de Juarez',
      'Amman Center for Human Rights Studies : Markaz ʻAmmān li-Dirāsāt Ḥuqūq al-Insān.',
      'Amnesty International',
      'Amnesty International Aotearoa New Zealand',
      'Amnesty International [Australia]',
      'Amnesty International Canada',
      'Amnesty International ČR',
      'Amnesty International [Danmark]',
      'Amnesty International Deutschland',
      'Amnesty International European Institutions Office',
      'Amnesty International [Finland]',
      'Amnesty International France',
      'Amnesty International, F�roya deild',
      'Amnesty International Ghana',
      'Amnesty International Hong Kong',
      'Amnesty International Hrvatske',
      'Amnesty International [Ireland]',
      'Amnesty International [Italy]',
      'Amnesty International : le site d\'Amnesty Belgique Francophone.',
      'Amnesty International Luxembourg',
      'Amnesty International Magyarország',
      'Amnesty International Mauritius Section',
      'Amnesty International Moldova',
      'Amnesty International Nepal',
      'Amnesty International [Netherlands]',
      'Amnesty International Nihon Shibu',
      'Amnesty International [Norge]',
      'Amnesty International Österreich',
      'Amnesty International Philippines',
      'Amnesty International Polska',
      'Amnesty International Schweiz',
      'Amnesty International, section Togo',
      'Amnesty International Sénégal',
      'Amnesty International Slovensko',
      'Amnesty International South Africa',
      'Amnesty International [Svenska sektionen]',
      'Amnesty International Taiwan = : Guo ji te she zu zhi Taiwan zong hui',
      'Amnesty International [Ukraine]',
      'Amnesty International [United Kingdom]',
      'Amnistía Internacional Bolivia',
      'Amnistía Internacional Chile',
      'Amnistía Internacional México',
      'Amnistia Internacional Portugal',
      'Amnistía Internacional Puerto Rico',
      'Amnistía Internacional, Sección Argentina',
      'Amnistía Internacional, Sección Española',
      'Amnistía Internacional, Sección Paraguaya',
      'Amnistía Internacional Uruguay',
      'Andalus Institute for Tolerance and Anti-Violence Studies',
      'ANDHES',
      'Anti Caste Discrimination Alliance',
      'Arab Association for Human Rights',
      'Arabic Network for Human Rights Information',
      'Arab Program for Human Rights Activists',
      'Argentine Forensic Anthropology Team : Equipo Argentino de Antropologia Forense.',
      'Article 19',
      'Asian Centre for Human Rights : dedicated to promotion and protection of human rights in Asia.',
      'Asian Federation Against Involuntary Disappearances',
      'Asian Forum for Human Rights and Development',
      'Asian Human Rights Commission',
      'Asian Legal Resource Centre',
      'Asia Pacific Forum : advancing human rights in our region.',
      'Asociación por los Derechos Civiles',
      'Asociación Pro Derechos Humanos',
      'ASPER : Associazione per la tutela dei diritti umani del popolo eritreo  = Association for the Defense of Human Rights of the Eritrean People.',
      'Assistance Association for Political Prisoners (Burma)',
      'Associação Justiça, Paz e Democracia : Justice, Peace and Democracy Association.',
      'Association for Freedom of Thought and Expression',
      'Association for the Prevention of Torture',
      'Association for Women\'s Rights in Development',
      'Association marocaine des droits humains',
      'Association pour le respect des droits de l\'homme à Djibouti : ARDHD.',
      'Association sahraouie des victimes des violations graves des droits de l\'homme commises par l\'Etat du Maroc',
      'Australian Human Rights Commission',
      'AWARE',
      'Baheyya : Egypt analysis and whimsy : commentary on Egyptian politics and culture by an Egyptian citizen with a room of her own.',
      'BAOBAB for Women\'s Human Rights',
      'Basel Action Network : BAN.',
      'Beogradski centar za ljudska prava',
      'Bermuda Ombudsman',
      'Bimkom',
      'breakthrough',
      'British Irish Rights Watch',
      'B\'Tselem : The Israeli information center for human rights in the occupied territories.',
      'Burma Lawyers\' Council',
      'Cageprisoners',
      'Cairo Institute for Human Rights Studies',
      'CALDH',
      'Cambodian League for the Promotion and Defense of Human Rights',
      'Campaign for Good Governance',
      'Canadian Friends of Burma',
      'CELS, Centro de Estudios Legales y Sociales',
      'Center for Economic and Social Rights',
      'Center for Justice and International Law',
      'Center for Social Development : Majhamandal saṃrap Qbhivadhṅ Sangaṃ',
      'Centre for Democratic Development, Research and Training',
      'Centre for Human Rights and Rehabilitation',
      'Centre for the Development of People',
      'Centre for Victims of Torture, Nepal',
      'Centre for War Victims and Human Rights',
      'Centro de Derechos Humanos Miguel Agustín Pro Juárez',
      'Centro de Estudios Sociales Padre Juan Montalvo, S.J.',
      'Centro de Justicia para la Paz y el Desarrollo',
      'Centro Nicaragüense de Derechos Humanos',
      'Child Rights Information & Documentation Centre',
      'Citizenship Rights in Africa Initiative',
      'Coalition for an Effective African Court on Human and Peoples\' Rights',
      'Coalition to Stop the Use of Child Soldiers',
      'Colectivo de Abogados José Alvear Restrepo',
      'Collectif des associations contre l\'impunité au Togo',
      'Comisionado Nacional de los Derechos Humanos',
      'Comisión Andina de Juristas',
      'Comisión de la Verdad y Reconciliación',
      'Comisión Mexicana de Defensa y Promoción de los Derechos Humanos',
      'Comisión Nacional de los Derechos Humanos, México',
      'Comissão de Acolhimento, Verdade, e Reconciliac̦ão de Timor-Leste',
      'Comité Cubano Pro Derechos Humanos',
      'Comité de Familiares de Detenidos-Desaparecidos en Honduras',
      'Comité para la Defensa de los Derechos Humanos en Honduras',
      'Comité sénégalaise des droits de l\'homme',
      'Commissie Gelijke Behandeling',
      'Commission for Human Rights and Good Governance',
      'Commission nationale consultative des droits de l\'homme',
      'Commission Nationale des Droits de l\'Homme du Togo',
      'Commission on Human Rights of the Philippines',
      'Committee to Protect Journalists',
      'Community Appraisal & Motivation Program',
      'CONECTAS Direitos Humanos',
      'Congolese Women\'s Campaign Against Sexual Violence in the Democratic Republic of the Congo (DRC)',
      'Conselho Indigenista Missionário',
      'Control arms',
      'Coordinadora de Derechos Humanos del Paraguay',
      'Coordinadora Nacional de Derechos Humanos',
      'Corporación de Promoción y Defensa de los Derechos del Pueblo',
      'CRLDHT--Comité pour le respect des libertés et des droits de l\'homme en Tunisie',
      'CSVR : Centre for the Study of Violence and Reconciliation.',
      'Danish Institute of Human Rights',
      'Darfur Consortium',
      'Defensor del Pueblo de la Nación',
      'Defensor del Pueblo, República de Bolivia',
      'Defensores en linea.com',
      'Defensoría del Pueblo de Ecuador',
      'Defensoría del Pueblo de la República de Panamá',
      'Defensoría del Pueblo [Peru]',
      'Defensoría del Pueblo, República del Paraguay',
      'Democracywatch',
      'Derechos Chile',
      'Deutsches Institut für Menschenrechte',
      'Diethnēs Amnēstia - Hellēniko Tmēma',
      'Diskrimineringsombudsmannen',
      'Ditshwanelo',
      'Down to Earth',
      'ECPAT International',
      'Egyptian Blog for Human Rights',
      'Egyptian Organization for Human Rights',
      'Electoral Institute of Southern Africa',
      'Empowerment and Rights Institute : Ren zhi quan gong zuo shi.',
      'Equality and Human Rights Commission',
      'Eritrean Human Rights Electronic Archive',
      'Ethiopian Human Rights Council',
      'European Roma Rights Center',
      'Famafrique',
      'FOCUS on the Global South',
      'FOHRID--Human Rights and Democratic Forum',
      'Fond za humanitarno pravo',
      'Fond zashchity glasnosti',
      'Forces de libération africaines de Mauritanie',
      'Forum for African Women Educationalists',
      'Foundation for Human Rights Initiative',
      'Friends of Tibet',
      'Front Line',
      'Fundación Centro de Derechos Humanos y Ambiente',
      'Fundación de Antropologia Forense de Guatemala : Forensic Anthropology Foundation of Guatemala.',
      'Fundación de Ayuda Social de las Iglesias Cristianas',
      'Fundación Regional de Asesoría en Derechos Humanos',
      'Fundación Vicaría de la Solidaridad',
      'Gabinete de Assessoria Jurídica as Organizaçoes Populares',
      'Galilee Society',
      'Generación Y',
      'Ghana Center for Democratic Development',
      'Global Alliance against Traffic in Women',
      'Global Witness',
      'Greensboro Truth & Community Reconciliation Project',
      'Greensboro Truth & Reconciliation Commission : seeking truth, working for reconciliation /',
      'Habitat International Coalition',
      'Hakielimu',
      'HaMoked--Center for the Defence of the Individual',
      'Hayastani Hanrapetutʻyan Mardu Irakunkʻneri Pashtpan',
      'Hayʼat al-Inṣāf wa-al-Muṣālaḥah',
      'Hellenic Republic, National Commission for Human Rights',
      'Helsinki Citizens\' Assembly Vanadzor Office',
      'Helsinki Committee for Human Rights in Serbia',
      'Héritiers de la Justice',
      'Human Rights Commission, New Zealand',
      'Human Rights Commission of Malaysia : Suruhanjaya Hak Asasi Manusia Malaysia.',
      'Human Rights Commission of Pakistan',
      'Human Rights Commission of Sri Lanka',
      'Human Rights Commission of the Maldives',
      'Human Rights Commission [Zambia]',
      'Human Rights Concern Eritrea',
      'Human Rights Congress for Bangladesh Minorities',
      'Human Rights Council of Australia',
      'Human Rights Education Institute of Burma',
      'Human Rights First',
      'Human Rights First Society',
      'humanrights.ge : web portal on human rights in Georgia = Veb portali adamianis upʻlebebis mesaxeb.',
      'Human Rights Law Network',
      'Human Rights Press Point',
      'IDASA',
      'I-India',
      'Independent Commission for Human Rights',
      'Indeso mujer',
      'INDICT',
      'Indigenous Peoples\' Center for Documentation, Research and Information',
      'Indigenous Peoples Council on Biocolonialism',
      'Indignación',
      'Informat︠s︡ionno-analiticheskiĭ t︠s︡entr "Sova"',
      'Inimõiguste keskus',
      'İnsan Hakları Ortak Platformu : Human Rights Joint Platform.',
      '"İnsan Hüquqları XXI ăsr-Azărbaycan" Fondu',
      'Institute for Justice and Reconciliation',
      'Instituto de Defensa Legal - IDL',
      'Instituto Espacio para la Memoria',
      'Instituto Latinoamericano para una Sociedad y un Derecho Alternativos',
      'International Campaign for Tibet',
      'International Coalition for the Responsibility to Protect',
      'International Commission of Jurists',
      'International Commission on Missing Persons',
      'International Committee Against Stoning',
      'International Committee for Democracy in Cuba',
      'International Committee of Solidarity for Political Prisoners in Tunisia',
      'International Criminal Tribunal for Rwanda',
      'International Crisis Group',
      'International Federation of Health and Human Rights Organisations',
      'International Federation of Iranian Refugees',
      'International Gay and Lesbian Human Rights Commission',
      'International League for Human Rights',
      'International Service for Human Rights',
      'International Society for Human Rights',
      'International Work Group for Indigenous Affairs',
      'Invisible Tibet : Woeser\'s blog.',
      'Iran Human Rights Documentation Center',
      'Iran Human Rights Voice',
      'Iraq Foundation',
      'Iraqi Human Rights Group',
      'Islamic Human Rights Commission',
      'Íslandsdeild Amnesty International',
      'Jamʻīyat Shabāb al-Baḥrayn li-Ḥuqūq al-Insān',
      'Jesuit Refugee Service',
      'Jesuit Refugee Service/USA',
      'Judicial System Monitoring Programme',
      'Jumma Peoples Network UK',
      'Justiça Global',
      'Kefayah',
      'Kenya Human Rights Commission',
      'Kenya National Commission on Human Rights',
      'Kgeikani Kweni, First People of the Kalahari',
      'Komitet pravnlka za ljudska prava',
      'Komnas HAM Indonesia',
      'Kosovakosovo.com',
      'Kurdish Human Rights Project',
      'Kurdish Women\'s Rights Watch',
      'Kuru Family of Organisations',
      'Kyrgyz Committee for Human Rights',
      'La Defensoria de los Habitantes',
      'Land Center for Human Rights',
      'Latin American and Caribbean Committee for the Defense of Women\'s Rights',
      'Latvian Centre for Human Rights',
      'Law & Society Trust',
      'Legal and Human Rights Centre',
      'Lembaga Studi dan Advokasi Masyarakat',
      'Ligue algerienne pour la defense des droits de l\'homme',
      'Ligue burundaise des droits de l\'homme',
      'Madre',
      'Malawi Human Rights Commission',
      'Malawi Human Rights Resource Centre',
      'MAP Foundation',
      'Mardu iravunkʻnerě Hayastanum',
      'Markaz al-Tawthīq wa-al-Iʻlām wa-al-Takwīn fī Majāl Ḥuqūq al-Insān',
      'Markaz Hishām Mubārak lil-Qānūn',
      'Mauritius National Human Rights Commission',
      'Mazlumder : İnsan Hakları ve Mazlumlar için Dayanışma Derneği = The Association of Human Rights and Solidarity for Oppressed People.',
      'Media Foundation for West Africa',
      'Memoria Abierta',
      'Mezan Center for Human Rights',
      'Minority Rights Group International',
      'Mongol Ulsyn Khu̇niĭ Ėrkhiĭn U̇ndėsniĭ Komiss',
      'Moskovskai︠a︡ khelʹsinkskai︠a︡ gruppa',
      'Mouvement contre les armes légères en Afrique de l\'Ouest',
      'Movimento dos Trabalhadores Rurais sem Terra',
      'Movimento Nacional dos Direitos Humanos',
      'Muʼassasat al-Marʼah al-Jadīdah',
      'Munaẓẓamah al-ʻArabīyah lil-Iṣlāḥ al-Jināʼī',
      'Munaẓẓamah al-Maghribīyah li-Ḥuqūq al-Insān : Organisation Marocaine des Droits Humains.',
      'NAMRIGHTS',
      'National Campaign on Dalit Human Rights',
      'National Centre for Human Rights [Jordan]',
      'National Council for Human Rights [Egypt]',
      'National Human Rights Commission, Nepal',
      'National Human Rights Commission, New Delhi, India',
      'National Human Rights Commission, Nigeria',
      'National Human Rights Commission of Korea',
      'National Human Rights Committee : Lajnah al-Waṭanīyah li-Ḥuqūq al-Insān.',
      'National Organization for Defending Rights and Freedoms',
      'National Protection Working Group (NWPG)',
      'National Unity and Reconciliation Commission',
      'NCHRO : National Confederation of Human Rights Organizations.',
      'Nemzeti és Etnikai Kisebbségi Jogok Országgyűlési Biztosa',
      'Network Movement for Justice and Development',
      'Network of Concerned Historians',
      'New Tactics in Human Rights',
      'NGO Coordination Committee for Iraq : Lajnat Tansīq al-Munaẓẓamāt Ghayr al-Ḥukūmiyah fī al-ʻIrāq.',
      'Northern Ireland Human Rights Commission',
      'Not On Our Watch',
      'Nuba Survival Foundation',
      'Observatorio Ciudadano',
      'Office of the National Human Rights Commission of Thailand',
      'Office of the Ombudsman [Namibia]',
      'Office of the Ombudsman of Trinidad and Tobago',
      'Oficina del Procurador del Ciudadano de Puerto Rico',
      'OMAL : Observatorio de Multinacionales en América  Latina.',
      'Ombudsman [Azerbaijan]',
      'Ombudsman Republike Srpske--zaštitnik ljudskih prava',
      'One Million Signatures Demanding Changes to Discriminatory Laws',
      'Organización Argentina de Jóvenes para las Naciones Unidas : OAJNU.',
      'Organizat︠s︡ii︠a︡ Drom',
      'Other Russia',
      'Pakistan International Human Rights Organization',
      'Palestinian Center for Human Rights',
      'Paz con Dignidad',
      'Peace Brigades International : making space for peace.',
      'Persian2English',
      'Physicians for Human Rights',
      'Plataforma Interamericana de Derechos Humanos, Democracia y Desarrollo',
      'Point Pedro Institute of Development.',
      'Portail de l\'Organisation TAMAYNUT',
      'Prava li︠u︡dyny v Ukraïni',
      'Pravovai︠a︡ init︠s︡iativa po Rossii',
      'Privacy International',
      'Procuraduria de los Derechos Humanos',
      'Procuraduría para la Defensa de los Derechos Humanos República de Nicaragua--América Central',
      'PROVEA : Programa Venezolano de Educación-Acción en Derechos Humanos.',
      'Pučki pravobranitelj : Ombudsman.',
      'Pukhan minjuhwa net\'ŭwŏk\'ŭ : Network for North Korean Democracy and Human Rights (NKnet).',
      'Qūwat al-ʻAmal li-Munāhaḍat al-Taʻdhīb',
      'Rabbis for Human Rights',
      'Ramallah Center for Human Rights Studies',
      'Rede Social de Justiça e Direitos Humanos',
      'Regional Watch for Human Rights',
      'Rencontre africaine pour la défense des droits de l\'homme',
      'Republika Makedonija naroden pravobranitel Ombudsman',
      'Réseau des journalistes pour les droits de l\'homme',
      'Réseau national de défense des droits humains--RNDDH',
      'RPHA "Belaruski khelʹsinkski kamitėt"',
      'Rrjeti i Grupeve të Grave të Kosovës',
      'Russian Association of Indigenous Peoples of the North, Siberia and the Far East',
      'Satellite Sentinel Project',
      'Sdružení Dženo',
      'Sección Peruana de Amnistía Internacional',
      'Shan Women\'s Action Network',
      'Shirkat Gah : women\'s resource centre.',
      'Sin Fronteras IAP',
      'Sokwanele',
      'Solidarity Peace Trust',
      'South African Human Rights Commission',
      'South Africa Truth and Reconciliation Commission',
      'South Asia Forum for Human Rights',
      'Srebrenica.ba',
      'Students for a Free Tibet',
      'Suara Rakyat Malaysia',
      'Survivor Corps',
      'Tanzania Gender Networking Programme',
      'Tapol',
      'Terra de Direitos : organização  de direitos humanos.',
      'The Advocates for Human Rights',
      'The Association for Civil Rights in Israel',
      'The Burma Campaign UK',
      'The Center for Democracy & Human Rights in Saudi Arabia',
      'The Center for Justice and Accountability',
      'The Committee for the Defense of Human Rights in the Arabian Peninsula',
      'The Egyptian Association for Community Participation Enhancement',
      'The Equal Rights Trust',
      'The Initiative for an Open Arab Internet',
      'The International Network for the Rights of Female Victims of Violence in Pakistan (INRFVVP)',
      'The Lawyers Centre for Legal Assistance',
      'The Palestinian Human Rights Monitoring Group',
      'The Rights Exposure Project',
      'ThinkCentre.org',
      'Tibetan Centre for Human Rights and Democracy',
      'TibetInfoNet',
      'Transition Monitoring Group, Nigeria',
      'Transparency International',
      'Truth and Reconciliation Commission of Liberia',
      'Truth and Reconciliation Commission, Republic of Korea : Chinsil, Hwahae rŭl wihan Kwagŏsa Chŏngni Wiwŏnhoe.',
      'Truth, Justice and Reconciliation Commission of Kenya',
      'T︠S︡entr informat︠s︡iï ta dokumentat︠s︡iï krymsʹkykh tatar',
      'Türkiye İnsan Hakları Vakfı',
      'Uganda Coalition on the International Criminal Court',
      'Uganda Human Rights Commission',
      'Uluslararası Af Örgütü--Türkiye',
      'Unity for Human Rights and Democracy Toronto',
      'University Teachers for Human Rights',
      'Unrepresented Nations and Peoples Organization',
      'Veřejný ochránce práv',
      'Vi︠a︡sna pravaabaronchy tsėntr',
      'Voix des Sans Voix',
      'Volksanwaltschaft',
      'Wa7damasrya',
      'Women for Afghan Women',
      'Women for Women\'s Human Rights',
      'Women Journalists Without Chains : Munaẓẓamat Ṣaḥafīyāt Bilā Quyūd.',
      'Women Living Under Muslim Laws : WLUML = Femmes Sous Lois Musulmanes.',
      'Women\'s Initiatives for Gender Justice',
      'WOREC Nepal',
      'World Organisation Against Torture',
      'Yemeni Human Rights Network',
      'Yemeni Organization for Defending Rights and Democratic Freedom',
      'Yesh Din--volunteers for human rights',
      'Zimbabwe Human Rights NGO Forum',
      'Zimbabwe Lawyers for Human Rights',
    ]
  end
end