# -*- encoding : utf-8 -*-
require 'rsolr-ext/response'
require 'rsolr-ext/response/docs'

# Blacklight::SolrHelper#get_search_results doesn't work with group queries,
# it causes a NoMethodError to be raised.
# https://github.com/cul/hrwa_blacklight/wiki/Grouped-Field-Collapsed-queries-Blacklight-workaround
module FieldCollapsedSolrHelper
  
  def get_search_results(user_params = params || {}, extra_controller_params = {})
    solr_response = stub
    document_list = []
    return [ solr_response, document_list ]
  end
  
  def stub
    return \
 {"responseHeader"=>
  {"status"=>0,
   "QTime"=>743,
   "params"=>
    {"f.contentMetaLanguage.facet.limit"=>"11",
     "facet"=>"true",
     "sort"=>"score desc",
     "group.limit"=>"10",
     "spellcheck.q"=>"+women",
     "q.alt"=>"*:*",
     "f.dateOfCaptureYYYY.facet.limit"=>"11",
     "f.organization_type__facet.facet.limit"=>"11",
     "f.language__facet.facet.limit"=>"11",
     "f.mimetype.facet.limit"=>"11",
     "group.field"=>"originalUrl",
     "facet.field"=>
      ["domain",
       "geographic_focus__facet",
       "organization_based_in__facet",
       "organization_type__facet",
       "language__facet",
       "contentMetaLanguage",
       "creator_name__facet",
       "mimetype",
       "dateOfCaptureYYYY"],
     "f.creator_name__facet.facet.limit"=>"11",
     "facet.mincount"=>"1",
     "qf"=>
      ["contentTitle^1",
       "contntBody^1",
       "contentMetaDescription^1",
       "contentMetaKeywords^1",
       "contentMetaLanguage^1",
       "contentBodyHeading1^1",
       "contentBodyHeading2^1",
       "contentBodyHeading3^1",
       "contentBodyHeading4^1",
       "contentBodyHeading5^1",
       "contentBodyHeading6^1"],
     "wt"=>"ruby",
     "f.geographic_focus__facet.facet.limit"=>"11",
     "defType"=>"dismax",
     "rows"=>"10",
     "f.domain.facet.limit"=>"11",
     "f.organization_based_in__facet.facet.limit"=>"11",
     "q"=>"+women",
     "group"=>"true"}},
 "grouped"=>
  {"originalUrl"=>
    {"matches"=>1064474,
     "groups"=>
      [{"groupValue"=>"http://www.hrw.org/he/keywords/women",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"contentTitle"=>"Taxonomy | Human Rights Watch",
             "originalUrl"=>"http://www.hrw.org/he/keywords/women",
             "dateOfCaptureYYYY"=>"2011",
             "statusCode"=>"200",
             "timestamp"=>"2011-09-29T21:39:45.041Z",
             "dateOfCaptureYYYYMMDD"=>"20110606",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20110606222047/http://www.hrw.org/he/keywords/women",
             "recordDate"=>"20110606222047",
             "contentMetaKeywords"=>"women",
             "recordIdentifier"=>
              "20110606222047/http://www.hrw.org/he/keywords/women",
             "contentBody"=>
              "Language Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© ä¸­æ–‡ English FranÃ§ais Deutsch ×¢×‘×¨×™×ª æ—¥æœ¬èªž Ð ÑƒÑÑÐºÐ¸Ð¹ EspaÃ±ol More + ×“×£ ×”×‘×™×ª ×—×“×©×•×ª ×¤×¨×¡×•×ž×™× ×ž×™ ×× ×—× ×• women ×ª×•×¨×›×™×”: × ×©×™× ××™× ×Ÿ ×–×•×›×•×ª ×œ×”×’× ×” ×ž×¤× ×™ ××œ×™×ž×•×ª ×ž××™ 4, 2011 ×”×ž×¢×¨×›×ª ×”×œ×§×•×™×” ×œ×”×’× ×” ×ž×¤× ×™ ××œ×™×ž×•×ª ×‘×ž×©×¤×—×” ×‘×ª×•×¨×›×™×” ×ž×¤×§×™×¨×” × ×©×™× ×•× ×¢×¨×•×ª ×‘×¨×—×‘×™ ×”×ž×“×™× ×” ×œ×œ× ×”×’× ×” ×ž×¤× ×™ ×”×ª×¢×œ×œ×•×ª ×‘×ª×•×š ×”×ž×©×¤×—×”. ×¤×¨×¦×•×ª ×‘×—×•×§ ×•×›×©×œ×™× ×‘××›×™×¤×ª×• ×ž×¨×—×™×§×™× ×ž×”×™×©×’ ×™×“×Ÿ ×©×œ × ×©×™× ×¨×‘×•×ª ×©× ×¤×’×¢×• ×”×’× ×•×ª ×”×¢×©×•×™×•×ª ×œ×”×¦×™×œ ××ª ×—×™×™×”×Ÿ, ×•×‘×›×œ×œ ×–×” ×¦×•×•×™ ×”×’× ×” ×©×œ ×‘×ª×™ ×ž×©×¤×˜ ×•×ž×§×œ×˜×™× ×œ×ž×¦×‘×™ ×—×™×¨×•×. ×—×“×©×•×ª × ×•×¡×¤×•×ªÂ» ×“×•×—×•×ª women ×ª×•×¨×›×™×”: × ×©×™× ××™× ×Ÿ ×–×•×›×•×ª ×œ×”×’× ×” ×ž×¤× ×™ ××œ×™×ž×•×ª ×ž××™ 4, 2011 ×”×ž×¢×¨×›×ª ×”×œ×§×•×™×” ×œ×”×’× ×” ×ž×¤× ×™ ××œ×™×ž×•×ª ×‘×ž×©×¤×—×” ×‘×ª×•×¨×›×™×” ×ž×¤×§×™×¨×” × ×©×™× ×•× ×¢×¨×•×ª ×‘×¨×—×‘×™ ×”×ž×“×™× ×” ×œ×œ× ×”×’× ×” ×ž×¤× ×™ ×”×ª×¢×œ×œ×•×ª ×‘×ª×•×š ×”×ž×©×¤×—×”. ×¤×¨×¦×•×ª ×‘×—×•×§ ×•×›×©×œ×™× ×‘××›×™×¤×ª×• ×ž×¨×—×™×§×™× ×ž×”×™×©×’ ×™×“×Ÿ ×©×œ × ×©×™× ×¨×‘×•×ª ×©× ×¤×’×¢×• ×”×’× ×•×ª ×”×¢×©×•×™×•×ª ×œ×”×¦×™×œ ××ª ×—×™×™×”×Ÿ, ×•×‘×›×œ×œ ×–×” ×¦×•×•×™ ×”×’× ×” ×©×œ ×‘×ª×™ ×ž×©×¤×˜ ×•×ž×§×œ×˜×™× ×œ×ž×¦×‘×™ ×—×™×¨×•×. More documents on this topicÂ» Back to top RSS ×“×£ ×”×‘×™×ª | ×—×“×©×•×ª | ×¤×¨×¡×•×ž×™× | ×ž×™ ×× ×—× ×• ×’×œ×™×©×” ×œ×¤×™ ××–×•×¨ ××¤×¨×™×§×” ××ž×¨×™×§×” ××¡×™×” ××™×¨×•×¤×”/×ž×¨×›×– ××¡×™×” ×”×ž×–×¨×— ×”×ª×™×›×•×Ÿ/×¦×¤×•×Ÿ ××¤×¨×™×§×” ××¨×¦×•×ª ×”×‘×¨×™×ª×’×œ×™×©×” ×œ×¤×™ ×ž×“×™× ×” ×’×œ×™×©×” ×œ×¤×™ × ×•×©× × ×©×§ ×¢×¡×§×™× ×–×›×•×™×•×ª ×™×œ×“×™× ×”×ž××‘×§ ×‘×˜×¨×•×¨ ×–×›×•×™×•×ª ×œ×× ×©×™× ×¢× ×ž×•×’×‘×œ×•×™×•×ª ×–×›×•×™×•×ª ×›×œ×›×œ×™×•×ª, ×—×‘×¨×ª×™×•×ª ×•×ª×¨×‘×•×ª×™×•×ª ×‘×¨×™××•×ª ×¦×“×§ ×‘×™× ×œ××•×ž×™ ×–×›×•×™×•×ª ×œ×”×˜\"×‘ ×ž×”×’×¨×™× ×—×•×¤×© ×”×¢×™×ª×•× ×•×ª ×¤×œ×™×˜×™× ×˜×¨×•×¨ ×¢×™× ×•×™×™× ×”××•×ž×•×ª ×”×ž××•×—×“×•×ª ×–×›×•×™×•×ª × ×©×™× Â© Copyright 2010, Human Rights Watch",
             "length"=>13970,
             "filename"=>
              "ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110606220953-00002-crawling207.us.archive.org-6680.warc.gz",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2011_06/ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110606220953-00002-crawling207.us.archive.org-6680.warc.gz",
             "digest"=>"sha1:JTTZZQQNH2MXEH4LHABXR2RT7Y6EFZNR",
             "mimetype"=>"text/html; charset=utf-8",
             "dateOfCaptureYYYYMM"=>"201106",
             "bib_key"=>"4391359",
             "organization_based_in__facet"=>"New York (State)",
             "organization_based_in"=>"New York (State)",
             "organization_type"=>"Non-governmental organizations",
             "organization_type__facet"=>"Non-governmental organizations",
             "website_original_urls"=>["http://www.hrw.org/"],
             "contentBodyHeading6"=>["women"],
             "contentBodyHeading5"=>[""],
             "contentBodyHeading4"=>[""],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>["×“×•×—×•×ª"],
             "contentBodyHeading1"=>[""],
             "geographic_focus"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "creator_name__facet"=>["Human Rights Watch (Organization)"],
             "geographic_focus__facet"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "domain"=>["www.hrw.org"],
             "creator_name"=>["Human Rights Watch (Organization)"],
             "language"=>["English"],
             "language__facet"=>["English"]}]}},
       {"groupValue"=>"http://www.hrw.org/es/keywords/women",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"contentTitle"=>"Taxonomy | Human Rights Watch",
             "originalUrl"=>"http://www.hrw.org/es/keywords/women",
             "dateOfCaptureYYYY"=>"2011",
             "statusCode"=>"200",
             "timestamp"=>"2011-09-29T21:39:51.012Z",
             "dateOfCaptureYYYYMMDD"=>"20110606",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20110606223240/http://www.hrw.org/es/keywords/women",
             "recordDate"=>"20110606223240",
             "contentMetaKeywords"=>"women",
             "recordIdentifier"=>
              "20110606223240/http://www.hrw.org/es/keywords/women",
             "contentBody"=>
              "Idioma Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© ä¸­æ–‡ English FranÃ§ais Deutsch ×¢×‘×¨×™×ª æ—¥æœ¬èªž Ð ÑƒÑÑÐºÐ¸Ð¹ EspaÃ±ol More + Portada Nuestro Trabajo Noticias Publicaciones Multimedia Sobre Nosotros Donar women TurquÃ­a: Mujeres desprotegidas ante la violencia Mayo 4, 2011 El defectuoso sistema de protecciÃ³n contra la violencia familiar en TurquÃ­a deja a mujeres y niÃ±as de todo el paÃ­s sin protecciÃ³n contra los abusos domÃ©sticos, seÃ±alÃ³ Human Rights Watch en un informe publicado hoy. Medidas de protecciÃ³n que podrÃ­an salvar vidas, incluidas las Ã³rdenes de protecciÃ³n dictadas por los tribunales y los refugios de emergencia, no se encuentran al alcance de muchas vÃ­ctimas de abusos debido a lagunas en la legislaciÃ³n y fallas en la aplicaciÃ³n de la ley. Reino Unido: Sistema de asilo por â€œvÃ­a rÃ¡pidaâ€ es injusto para las mujeres Feb 23, 2010 Las mujeres que temen graves violaciones a los derechos humanos si son devueltas a sus paÃ­ses de origen no estÃ¡n recibiendo la consideraciÃ³n justa a sus solicitudes de asilo bajo el sistema de asilo acelerado del Reino Unido. MÃ¡s noticias Â» Informes women TurquÃ­a: Mujeres desprotegidas ante la violencia Mayo 4, 2011 El defectuoso sistema de protecciÃ³n contra la violencia familiar en TurquÃ­a deja a mujeres y niÃ±as de todo el paÃ­s sin protecciÃ³n contra los abusos domÃ©sticos, seÃ±alÃ³ Human Rights Watch en un informe publicado hoy. Medidas de protecciÃ³n que podrÃ­an salvar vidas, incluidas las Ã³rdenes de protecciÃ³n dictadas por los tribunales y los refugios de emergencia, no se encuentran al alcance de muchas vÃ­ctimas de abusos debido a lagunas en la legislaciÃ³n y fallas en la aplicaciÃ³n de la ley. Reino Unido: Sistema de asilo por â€œvÃ­a rÃ¡pidaâ€ es injusto para las mujeres Feb 23, 2010 Las mujeres que temen graves violaciones a los derechos humanos si son devueltas a sus paÃ­ses de origen no estÃ¡n recibiendo la consideraciÃ³n justa a sus solicitudes de asilo bajo el sistema de asilo acelerado del Reino Unido. More documents on this topicÂ» Back to top RSS Portada | Nuestro Trabajo | Noticias | Publicaciones | Multimedia | Sobre Nosotros | Donar Human Rights Watch 350 Fifth Avenue, 34th Floor New York, NY 10118-3299 USA Tel: 1-(212) 290-4700 Fax: 1-(212) 736-1300 BÃºsqueda por regiÃ³n Ãfrica AmÃ©ricas Asia Europa/Asia Central Oriente Medio/Ãfrica del Norte Estados Unidos BÃºsqueda por paÃ­s BÃºsqueda por tema Armas Negocios Derechos del NiÃ±o Contraterrorismo Derechos de personas con discapacidad Derechos econÃ³micos, sociales y culturales Salud Justicia internacional Derechos de LGBT Migrantes Libertad de prensa Refugiados Terrorismo Tortura Naciones Unidas Derechos de la Mujer Â© Copyright 2010, Human Rights Watch",
             "length"=>17089,
             "filename"=>
              "ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110606220953-00002-crawling207.us.archive.org-6680.warc.gz",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2011_06/ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110606220953-00002-crawling207.us.archive.org-6680.warc.gz",
             "digest"=>"sha1:G4WW5I26EPHCPFQ6SZOMBQU2MBYN7ASA",
             "mimetype"=>"text/html; charset=utf-8",
             "dateOfCaptureYYYYMM"=>"201106",
             "bib_key"=>"4391359",
             "organization_based_in__facet"=>"New York (State)",
             "organization_based_in"=>"New York (State)",
             "organization_type"=>"Non-governmental organizations",
             "organization_type__facet"=>"Non-governmental organizations",
             "website_original_urls"=>["http://www.hrw.org/"],
             "contentBodyHeading6"=>["women"],
             "contentBodyHeading5"=>[""],
             "contentBodyHeading4"=>[""],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>["Informes"],
             "contentBodyHeading1"=>[""],
             "geographic_focus"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "creator_name__facet"=>["Human Rights Watch (Organization)"],
             "geographic_focus__facet"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "domain"=>["www.hrw.org"],
             "creator_name"=>["Human Rights Watch (Organization)"],
             "language"=>["English"],
             "language__facet"=>["English"]}]}},
       {"groupValue"=>"http://www.hrw.org/en/keywords/women",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"contentTitle"=>"women | Human Rights Watch",
             "originalUrl"=>"http://www.hrw.org/en/keywords/women",
             "dateOfCaptureYYYY"=>"2011",
             "statusCode"=>"200",
             "timestamp"=>"2011-09-29T21:41:54.223Z",
             "dateOfCaptureYYYYMMDD"=>"20110607",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20110607054349/http://www.hrw.org/en/keywords/women",
             "recordDate"=>"20110607054349",
             "contentMetaKeywords"=>"women",
             "recordIdentifier"=>
              "20110607054349/http://www.hrw.org/en/keywords/women",
             "contentBody"=>
              "Language Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© ä¸­æ–‡ English FranÃ§ais Deutsch ×¢×‘×¨×™×ª æ—¥æœ¬èªž Ð ÑƒÑÑÐºÐ¸Ð¹ EspaÃ±ol More + Policy Makers Press Get Involved Home Our Work News Publications Multimedia About Us Donate women Turkey: Women Left Unprotected From Violence May 4, 2011 (Istanbul) - Turkey's flawed family violence protection system leaves women and girls across the country unprotected against domestic abuse, Human Rights Watch said in a report released today. Life-saving protections, including court-issued protection orders and emergency shelters, are not available for many abuse victims because of gaps in the law and enforcement failures. UK: â€˜Fast Trackâ€™ Asylum System Fails Women Feb 23, 2010 Women who fear severe human rights abuses if returned to their home countries are not getting fair consideration of their asylum claims under the United Kingdomâ€™s â€œdetained fast trackâ€ asylum system. More newsÂ» Reports women Turkey: Women Left Unprotected From Violence May 4, 2011 (Istanbul) - Turkey's flawed family violence protection system leaves women and girls across the country unprotected against domestic abuse, Human Rights Watch said in a report released today. Life-saving protections, including court-issued protection orders and emergency shelters, are not available for many abuse victims because of gaps in the law and enforcement failures. Only Half a Revolution? Mar 9, 2011 The images of Egyptians standing side by side in Tahrir Square inspired and captured the attention of the world. During the 18 days of protests that led to Hosni Mubarak's downfall, women and men stood together to demand their freedom and human rights. How Settling With the Taliban Puts Women at Risk Aug 15, 2010 \"If you had to choose between saving a girl's life or enabling her to go to school, which would you do first?\" This was Afghan President Hamid Karzai's reply when I asked him last month if the rights of Afghan women might be sacrificed for a peace settlement with the Taliban. How the UAE Condones Sexual Violence Jun 29, 2010 Attitudes in the Emirates towards women may have improved, but the punishment of those who report rape is a scandal. UK: â€˜Fast Trackâ€™ Asylum System Fails Women Feb 23, 2010 Women who fear severe human rights abuses if returned to their home countries are not getting fair consideration of their asylum claims under the United Kingdomâ€™s â€œdetained fast trackâ€ asylum system. Letter to Papua New Guinea Minister of Justice Jan 26, 2009 Open Letter to the Government of Macedonia Regarding Criminal Prosecution of Alleged Sex Workers Dec 17, 2008 In a letter to the government of Macedonia, the undersigned, supporters and representatives of sex workers and organizations and individuals advocating for human rights, strongly condemn police actions in relation to the recent mass arrest of alleged sex workers in Skopje, Macedonia. More documents on this topicÂ» Back to top RSS Home | Our Work | News | Publications | Multimedia | About Us | Donate Human Rights Watch 350 Fifth Avenue, 34th Floor New York, NY 10118-3299 USA Tel: 1-(212) 290-4700 Contact Us - Global Offices Film Festival Employment Browse by Region Africa Americas Asia Europe/Central Asia Middle East/N. Africa United StatesBrowse by Country Browse by Topic Arms Business Children's Rights Counterterrorism Disability Rights ESC Rights Health International Justice LGBT Rights Migrants Press Freedom Refugees Terrorism Torture United Nations Women's Rights Site Map | Privacy Policy | Corrections | Permissions Â© Copyright 2010, Human Rights Watch",
             "length"=>19954,
             "filename"=>
              "ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110607044225-00021-crawling207.us.archive.org-6680.warc.gz",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2011_06/ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110607044225-00021-crawling207.us.archive.org-6680.warc.gz",
             "digest"=>"sha1:QY4XD7BFV3OAJMRQX2BDOTLJWA6DWGBQ",
             "mimetype"=>"text/html; charset=utf-8",
             "dateOfCaptureYYYYMM"=>"201106",
             "bib_key"=>"4391359",
             "organization_based_in__facet"=>"New York (State)",
             "organization_based_in"=>"New York (State)",
             "organization_type"=>"Non-governmental organizations",
             "organization_type__facet"=>"Non-governmental organizations",
             "website_original_urls"=>["http://www.hrw.org/"],
             "contentBodyHeading6"=>["women"],
             "contentBodyHeading5"=>[""],
             "contentBodyHeading4"=>[""],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>["Reports"],
             "contentBodyHeading1"=>[""],
             "geographic_focus"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "creator_name__facet"=>["Human Rights Watch (Organization)"],
             "geographic_focus__facet"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "domain"=>["www.hrw.org"],
             "creator_name"=>["Human Rights Watch (Organization)"],
             "language"=>["English"],
             "language__facet"=>["English"]}]}},
       {"groupValue"=>"http://www.hrw.org/fr/keywords/women",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"contentTitle"=>"Taxonomy | Human Rights Watch",
             "originalUrl"=>"http://www.hrw.org/fr/keywords/women",
             "dateOfCaptureYYYY"=>"2011",
             "statusCode"=>"200",
             "timestamp"=>"2011-09-29T21:44:10.051Z",
             "dateOfCaptureYYYYMMDD"=>"20110607",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20110607143029/http://www.hrw.org/fr/keywords/women",
             "recordDate"=>"20110607143029",
             "contentMetaKeywords"=>"women",
             "recordIdentifier"=>
              "20110607143029/http://www.hrw.org/fr/keywords/women",
             "contentBody"=>
              "Langue Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© ä¸­æ–‡ English FranÃ§ais Deutsch ×¢×‘×¨×™×ª æ—¥æœ¬èªž Ð ÑƒÑÑÐºÐ¸Ð¹ EspaÃ±ol More + Accueil Notre travail ActualitÃ©s Rapports Ã€ propos de Faites un don women Turquie : Les femmes laissÃ©es sans protection contre la violence Mai 4, 2011 A cause des lacunes du systÃ¨me turc de protection contre la violence familiale, les femmes et les jeunes filles restent Ã  la merci des violences domestiques dans l'ensemble du pays, a affirmÃ© Human Rights Watch dans un rapport publiÃ© aujourd'hui. Les protections vitales, comme les ordonnances de protection dÃ©livrÃ©es par les tribunaux et les centres d'accueil d'urgence restent hors de portÃ©e pour de nombreuses victimes de violences, du fait des lacunes de la loi et de dÃ©faillances dans son application. Suite Â» Rapports women Turquie : Les femmes laissÃ©es sans protection contre la violence Mai 4, 2011 A cause des lacunes du systÃ¨me turc de protection contre la violence familiale, les femmes et les jeunes filles restent Ã  la merci des violences domestiques dans l'ensemble du pays, a affirmÃ© Human Rights Watch dans un rapport publiÃ© aujourd'hui. Les protections vitales, comme les ordonnances de protection dÃ©livrÃ©es par les tribunaux et les centres d'accueil d'urgence restent hors de portÃ©e pour de nombreuses victimes de violences, du fait des lacunes de la loi et de dÃ©faillances dans son application. More documents on this topicÂ» Back to top RSS Accueil | Notre travail | ActualitÃ©s | Rapports | Ã€ propos de | Faites un don RÃ©gions Afrique AmÃ©riques Asie Europe/Asie centrale Moyen Orient/Afrique du Nord Ã‰tats-Unis Pays ThÃ¨mes Armes Monde de l'entreprise Droits de l'enfant Lutte antiterroriste Droits des personnes handicapÃ©es Droits Ã©conomiques, sociaux et culturels SantÃ© Justice internationale Droits LGBT Migrants LibertÃ© de la presse RÃ©fugiÃ©s Terrorisme Torture Nations Unies Droits des femmes Â© Copyright 2010, Human Rights Watch",
             "length"=>14164,
             "filename"=>
              "ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110607131404-00033-crawling207.us.archive.org-6680.warc.gz",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2011_06/ARCHIVEIT-1068-BIMONTHLY-QXGACE-20110607131404-00033-crawling207.us.archive.org-6680.warc.gz",
             "digest"=>"sha1:6AURPJVALKWLA2H2HUXCF7BFYL73JAJP",
             "mimetype"=>"text/html; charset=utf-8",
             "dateOfCaptureYYYYMM"=>"201106",
             "bib_key"=>"4391359",
             "organization_based_in__facet"=>"New York (State)",
             "organization_based_in"=>"New York (State)",
             "organization_type"=>"Non-governmental organizations",
             "organization_type__facet"=>"Non-governmental organizations",
             "website_original_urls"=>["http://www.hrw.org/"],
             "contentBodyHeading6"=>["women"],
             "contentBodyHeading5"=>[""],
             "contentBodyHeading4"=>[""],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>["Rapports"],
             "contentBodyHeading1"=>[""],
             "geographic_focus"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "creator_name__facet"=>["Human Rights Watch (Organization)"],
             "geographic_focus__facet"=>[" [043 CODE NOT FOUND IN MARC LIST]"],
             "domain"=>["www.hrw.org"],
             "creator_name"=>["Human Rights Watch (Organization)"],
             "language"=>["English"],
             "language__facet"=>["English"]}]}},
       {"groupValue"=>"http://khpg.org/en/index.php?do=print&id=1272455398",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"digest"=>"sha1:YTEJYSMS2UOOI7PKB3DUN4JOOHX4CSFZ",
             "filename"=>
              "ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "length"=>5938,
             "mimetype"=>"text/html",
             "originalUrl"=>
              "http://khpg.org/en/index.php?do=print&id=1272455398",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2010_09/ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "recordDate"=>"20100904153026",
             "recordIdentifier"=>
              "20100904153026/http://khpg.org/en/index.php?do=print&id=1272455398",
             "statusCode"=>"200",
             "dateOfCaptureYYYY"=>"2010",
             "dateOfCaptureYYYYMM"=>"201009",
             "dateOfCaptureYYYYMMDD"=>"20100904",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20100904153026/http://khpg.org/en/index.php?do=print&id=1272455398",
             "contentBody"=>
              "Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group http://khpg.org.index.php?id=1272455398 Womenï¿½s rights So what is positive in restricting womenï¿½s right to take part in government? 28.04.10 Kateryna Levchenko, President of the International Womenï¿½s Human Rights Centre La Strada ï¿½ Ukraine, has no intention of giving up her battle against the extraordinarily discriminatory remarks and actions of the countryï¿½s leaders. In a blog entry on Ukrainska Pravda she notes that the Prime Ministerï¿½s statement that ï¿½carrying out reforms is not a womanï¿½s matterï¿½ had been forgotten amid the events over the agreement on the Black Sea Fleet with Russia, the judgment of the Constitutional Court [overturning its judgment of 18 months ago to this time effectively legitimize the present government] and subsequent increase in number of coalition members. She stresses, however, that the remarks which outraged people both in Ukraine and abroad can not be put aside since no legal assessment by the authorities has yet been forthcoming despite the fact that the month allowed for reviewing complaints from the public has now passed. As we reported, representatives of different womenï¿½s groups lodged a formal complaint with the Ministry for the Family, Youth and Sport, which is the authorized body on forming and implementing gender policy in the country. The complaint addressed to the Minister stated that Prime Minister Azarovï¿½s remark, in their view, clearly constituted discrimination as per Article 1 of the Law on ensuring equal rights and opportunities for men and women. It also prevented recognition of the enjoyment and exercising on an equal basis of rights and opportunities, these including the right to take part in governance, the right to freely elect and be elected to public authorities and bodies of local self-government, the right of equal access to the civil service, as well as work in bodies of local self-government. Ms Levchenko points out that such discrimination is also in breach of Article 24 of the Constitution which states that citizens have equal constitutional rights and freedoms and are equal before the law. The complaint also cited the many international documents which guarantee such rights. ï¿½And what was the response?ï¿½ It states that the ï¿½speech by Prime Minister Azarov on 19.03.2010 does not fall under the concept of ï¿½discrimination on the basis of genderï¿½. The author is forced to conclude that the specialists in the Ministry regard such restrictions, i.e. women not being seen as suitable implementers of reforms, as ï¿½positive actionsï¿½. Their letter states: ï¿½According to Article 6 of the above-mentioned Law positive actions are not deemed discrimination on the basis of gender. Also pursuant to Article 16 of this Law appointment to the civil service and service in bodies of local self-government is carried out observance representation of candidates of both sex. It is permitted to apply positive actions in order to achieve balanced representation of men and women in the civil service in bodies of local self-government, bearing in mind the categories of civil servantsï¿½ posts.ï¿½ The author repeats that the only conclusion possible is that restrictions preventing women from taking part in reforms, which the Prime Minister spoke of, are ï¿½positive actionsï¿½. She quotes a number of international documents which do indeed allow for positive discrimination, i.e. temporary measures aimed at rectifying the imbalance in the number of men and women. Ms Levchenko points out that the law quite legitimately does not itemize ï¿½positive actionsï¿½. She notes that in many European countries these can be electoral quotas or other forms of positive discrimination. For the first time, and in a Cabinet of Ministers whose size breaks records in Europe, there is not one single woman. The battle thus continues. Information from Kateryna Levchenkoï¿½s article here: www.pravda.com.ua see olso: \u0095 Ukraine lagging behind in number of women in high office \u0095 Ukrainian women vs. Azarov \u0095 Prime Minister Azarov to answer charges of discrimination in court \u0095 Complaint to Human Rights Ombudsperson over Azarovï¿½s discriminatory comments \u0095 Azarov: Carrying out reform is not a womanï¿½s matter",
             "contentTitle"=>"",
             "timestamp"=>"2011-09-30T17:55:06.78Z",
             "contentBodyHeading6"=>[""],
             "contentBodyHeading5"=>["Womenï¿½s rights"],
             "contentBodyHeading4"=>
              ["Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group"],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>[""],
             "contentBodyHeading1"=>
              ["So what is positive in restricting womenï¿½s right to take part in government?"]}]}},
       {"groupValue"=>"http://khpg.org/en/index.php?do=print&id=1270822714",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"digest"=>"sha1:FQFO3BEPFBDE5ILK4EKKW75GBXJ62MXT",
             "filename"=>
              "ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "length"=>3979,
             "mimetype"=>"text/html",
             "originalUrl"=>
              "http://khpg.org/en/index.php?do=print&id=1270822714",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2010_09/ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "recordDate"=>"20100904153107",
             "recordIdentifier"=>
              "20100904153107/http://khpg.org/en/index.php?do=print&id=1270822714",
             "statusCode"=>"200",
             "dateOfCaptureYYYY"=>"2010",
             "dateOfCaptureYYYYMM"=>"201009",
             "dateOfCaptureYYYYMMDD"=>"20100904",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20100904153107/http://khpg.org/en/index.php?do=print&id=1270822714",
             "contentBody"=>
              "Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group http://khpg.org.index.php?id=1270822714 Womenï¿½s rights Ukraine lagging behind in number of women in high office 09.04.10 | www.golosua.com According to the Head of the Board of the Ukrainian Womenï¿½s Fund, Natalya Karbovska, Ukraine has a pretty low number of women holding high-ranking public office. She believes this is unacceptable in a country where 54% of the population are women. Commenting on the recent comments by Prime Minister Azarov about the lack of women in his Cabinet of Ministers, Ms Karbovska said that Ukrainian politicians had always managed to stun their fellow citizens with their comments, but that these were in a class of their own. ï¿½A womanï¿½s place is not only in the kitchen. When Azarov states that reforms are not womenï¿½s matter, he forces us to feel outrage and to stress that Ukraine, which just last year in terms of gender representation was in the middle of the list, is now in second to last place among countries of Africa and developing countriesï¿½. Natalya Karbovska cited statistics showing that only 7.5% of parliamentarians are women, but noted that this was in fact one of the highest figures, and gave the following: advisors to the President ï¿½ 0%; Cabinet of Ministers ï¿½ 0%; top echelons of the Verkhovna Rada, including the Speaker and his (!) deputies ï¿½ 0%; heads of Verkhovna Rada committees ï¿½ 7%; heads of regional (oblast) State Administrations and that of the Crimea ï¿½ 0%. The best situation is with deputies of regional councils where women make up 12%; district (raion) councils ï¿½ 23%; city councils ï¿½ 28%; and among higher category civil servants 18% are womenï¿½.ï¿½ She stressed that the level of powers and opportunities for women to influence national level decisions was much lower. Elli Valentine from the Support Programme for Ukraineï¿½s Parliamentï¿½ notes that normally the number of women in parliament is around 30%ï¿½ ï¿½ï¿½20% - in European countries, 30% - in the USA. ï¿½As an example: women make up 13.2% in parliament in the Russian Federation; Latvia ï¿½ï¿½ 22%, Poland ï¿½ï¿½ 20%, Sweden ï¿½ 42%. Belgium ï¿½ï¿½ 43%. The highest figure is in Rwanda ï¿½ï¿½ 50%. Against this background the figure of 7.5% in Ukraine is disturbingï¿½, she said. see olso: \u0095 So what is positive in restricting womenï¿½s right to take part in government? \u0095 Ukrainian women vs. Azarov \u0095 Prime Minister Azarov to answer charges of discrimination in court \u0095 Complaint to Human Rights Ombudsperson over Azarovï¿½s discriminatory comments \u0095 Azarov: Carrying out reform is not a womanï¿½s matter",
             "contentTitle"=>"",
             "timestamp"=>"2011-09-30T17:55:10.461Z",
             "contentBodyHeading6"=>[""],
             "contentBodyHeading5"=>["Womenï¿½s rights"],
             "contentBodyHeading4"=>
              ["Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group"],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>[""],
             "contentBodyHeading1"=>
              ["Ukraine lagging behind in number of women in high office"]}]}},
       {"groupValue"=>"http://khpg.org/en/index.php?do=print&id=1270551304",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"digest"=>"sha1:XVSYPTXEPP5O6QE2VJMNHTBLMB3UDP24",
             "filename"=>
              "ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "length"=>4499,
             "mimetype"=>"text/html",
             "originalUrl"=>
              "http://khpg.org/en/index.php?do=print&id=1270551304",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2010_09/ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "recordDate"=>"20100904153148",
             "recordIdentifier"=>
              "20100904153148/http://khpg.org/en/index.php?do=print&id=1270551304",
             "statusCode"=>"200",
             "dateOfCaptureYYYY"=>"2010",
             "dateOfCaptureYYYYMM"=>"201009",
             "dateOfCaptureYYYYMMDD"=>"20100904",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20100904153148/http://khpg.org/en/index.php?do=print&id=1270551304",
             "contentBody"=>
              "Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group http://khpg.org.index.php?id=1270551304 Womenï¿½s rights Ukrainian women vs. Azarov 06.04.10 | www.dw-world.de Prominent Ukrainian activists are using the courts to fight sexist statements from those in power, however lawyers are not optimistic about the prospects for such civil suits. The suit lodged with the Pechersky District Court in Kyiv claiming a violation by the Prime Minister of the constitutional right to gender equality requires clarification by 10 April. However one of the claimants, Head of La Strada â€“ Ukraine, Kateryna Levchenko explains: â€œA great deal of what clarification is sought on is already in the civil suit in which I ask for Mykola Azarovâ€™s remarks in Dnipropetrovsk where he said that â€œcarrying out reform in Ukraine is not a womanâ€™s matterâ€ to be declared discriminatory, and demand moral compensation of 1 UAHâ€. Ms Levchenko is convinced that they will do anything to stall the suit, however she has no intention of backing down and hopes in this way to draw attention to the issue of gender discrimination in the country. She says that once all domestic avenues are exhausted, there are possibilities for defending ones rights at an international level. There is, for example, procedure for submitting individual complaints to the UN Committee on the Convention for Fighting all Forms of Discrimination against Women. Lawyers are sceptical Kyiv lawyer Viacheslav Yakubenko does not see much prospect for the civil suit. â€œIn some cases public campaigns are much more effective than turning to the courtâ€. As reported, Ms Levchenkoâ€™s suit is one of two: Olena Suslova, Head of the Information and Consultative Womenâ€™s Centre has also filed a suit alleging violation of constitutional right to gender equality, however in her case the respondent is not the Prime Minister alone, but the Cabinet of Ministers as a whole. The Cabinet of Ministers press service earlier claimed that the Prime Ministerâ€™s words had been distorted, and that he had simply been saying that women were not able to put in so many hours of work. However Ms Levchenko is adamant that there is a recording of his address and that there was no distortion. She says that they have also lodged a complaint with the Human Rights Ombudsperson, however there has been no response. From a report by Olha Vesnyanka at www.dw-world.de see olso: \u0095 So what is positive in restricting womenï¿½s right to take part in government? \u0095 Ukraine lagging behind in number of women in high office \u0095 Prime Minister Azarov to answer charges of discrimination in court \u0095 Complaint to Human Rights Ombudsperson over Azarovï¿½s discriminatory comments \u0095 Azarov: Carrying out reform is not a womanï¿½s matter",
             "contentTitle"=>"",
             "timestamp"=>"2011-09-30T17:55:14.853Z",
             "contentBodyHeading6"=>[""],
             "contentBodyHeading5"=>["Womenï¿½s rights"],
             "contentBodyHeading4"=>
              ["Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group"],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>[""],
             "contentBodyHeading1"=>["Ukrainian women vs. Azarov"]}]}},
       {"groupValue"=>"http://khpg.org/en/index.php?do=print&id=1270203432",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"digest"=>"sha1:IINTMIDQKICXR6RS4CEWBG4FN23YAWYI",
             "filename"=>
              "ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "length"=>4630,
             "mimetype"=>"text/html",
             "originalUrl"=>
              "http://khpg.org/en/index.php?do=print&id=1270203432",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2010_09/ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "recordDate"=>"20100904153228",
             "recordIdentifier"=>
              "20100904153228/http://khpg.org/en/index.php?do=print&id=1270203432",
             "statusCode"=>"200",
             "dateOfCaptureYYYY"=>"2010",
             "dateOfCaptureYYYYMM"=>"201009",
             "dateOfCaptureYYYYMMDD"=>"20100904",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20100904153228/http://khpg.org/en/index.php?do=print&id=1270203432",
             "contentBody"=>
              "Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group http://khpg.org.index.php?id=1270203432 Womenï¿½s rights Prime Minister Azarov to answer charges of discrimination in court 02.04.10 Kateryna Levchenko, President of the International Womenï¿½s Human Rights Centre La Strada ï¿½ Ukraine and Olena Suslova, Head of the Information and Consultative Womenï¿½s Centre have filed law suits against the Prime Minister, Mykola Azarov. Their suits, lodged with the Pechersky District Court in Kyiv assert that the Prime Minister violated the constitutional norm on the equality of men and women. As reported here, Mr Azarov stated that ï¿½carrying out reform in Ukraine is not a womanï¿½s matterï¿½. He claimed that in the new government people had been chosen who can work 16 hours a day ï¿½without weekends and days offï¿½, can take responsibility and are not afraid to say no to the leadership. Earlier this week, the Cabinet of Ministers press service claimed that the Prime Ministerï¿½s words had been distorted, and that he had simply been saying that women were not able to put in so many hours of work. However Ms Levchenko is adamant that there is a recording of his address and that there was no distortion. ï¿½We have enclosed with our law suit a disk with the recording of Mykola Yanovychï¿½s speech in Dnipropetrovsk on 19 March where he clearly and distinctly says: ï¿½Reform is not a womanï¿½s matterï¿½. These words are not subject to two interpretations. He said what he wanted to say ï¿½ that a womanï¿½s place is in the kitchen, and not in the government.ï¿½ In an article on Ukrainska Pravda entitled ï¿½Why I took the Prime Minister to courtï¿½ (www.pravda.com.ua ), Kateryna Levchenko explains that she has simply had enough. ï¿½ï¿½This was not, after all, the first staggering utterance from those now in power. When Viktor Yanukovych, as presidential candidate, refused to take part in a television debate with Yulia Tymoshenko, attributed by many commentators to his reluctance to be outshined by a powerful and eloquent debater, he ended with the words: ï¿½If she is a woman, she should go to the kitchen and demonstrate her skills thereï¿½. The Cabinet of Ministers formed after parliament passed a law changing the Verkhovna Rada Regulations on coalition formation, has a record number of ministers and not one woman. And then came the ï¿½gemï¿½ from Mr Azarov, which Ms Levchenko describes as follows ï¿½Azarovï¿½s words are a public statement by a high-ranking government official which result in my personal rights and legitimate interests being violated, obstructions being put in the way of my exercising the constitutional right to take part in governance. They are also a demonstration of direct discrimination, that is, infringe the norms of the Constitution which are norms of direct force.ï¿½ ï¿½ see olso: \u0095 So what is positive in restricting womenï¿½s right to take part in government? \u0095 Ukraine lagging behind in number of women in high office \u0095 Ukrainian women vs. Azarov \u0095 Complaint to Human Rights Ombudsperson over Azarovï¿½s discriminatory comments \u0095 Azarov: Carrying out reform is not a womanï¿½s matter",
             "contentTitle"=>"",
             "timestamp"=>"2011-09-30T17:55:22.715Z",
             "contentBodyHeading6"=>[""],
             "contentBodyHeading5"=>["Womenï¿½s rights"],
             "contentBodyHeading4"=>
              ["Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group"],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>[""],
             "contentBodyHeading1"=>
              ["Prime Minister Azarov to answer charges of discrimination in court"]}]}},
       {"groupValue"=>"http://khpg.org/en/index.php?do=print&id=1269350026",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"digest"=>"sha1:OMAKO5447VX7WC7NQASCWDCKOJAP5AMM",
             "filename"=>
              "ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "length"=>4559,
             "mimetype"=>"text/html",
             "originalUrl"=>
              "http://khpg.org/en/index.php?do=print&id=1269350026",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2010_09/ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904151955-01207-crawling04.us.archive.org-6682.warc.gz",
             "recordDate"=>"20100904153309",
             "recordIdentifier"=>
              "20100904153309/http://khpg.org/en/index.php?do=print&id=1269350026",
             "statusCode"=>"200",
             "dateOfCaptureYYYY"=>"2010",
             "dateOfCaptureYYYYMM"=>"201009",
             "dateOfCaptureYYYYMMDD"=>"20100904",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20100904153309/http://khpg.org/en/index.php?do=print&id=1269350026",
             "contentBody"=>
              "Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group http://khpg.org.index.php?id=1269350026 Womenï¿½s rights Complaint to Human Rights Ombudsperson over Azarovï¿½s discriminatory comments 23.03.10 For the first time a complaint has been submitted to Ukraineâ€™s Human Rights Ombudsperson over sexual discrimination by the Prime Minister. As reported already, on 19 March, Prime Minister Mykola Azarov stated, after presenting the new Governor of the Dnipropetrovsk region, Oleksandr Vilkul, the following: â€œSome say that our government is large, others that it doesnâ€™t have any women in it, thereâ€™s nobody to look at during a Cabinet of Ministers meeting. The most boring people. With all due respect to women, carrying out reforms is not a womanâ€™s matterâ€.Â  He claimed that in the new government people had been chosen who can work 16 hours a day â€œwithout weekends and days offâ€, can take responsibility and are not afraid to say no to the leadership. The remarks received wide coverage both on websites and television channels. In response, a number of civic organizations have lodged a complaint (No. 148070 10/26) with Nina Karpachova, the Human Rights Ombudsperson alleging sexual discrimination by the Prime Minister. They are the Information and Consultation Womenâ€™s Centre, the International Womenâ€™s Human Rights Centre La Strada â€“ Ukraine; the civic organization â€œ50/50â€; the School of Equal Opportunitiesâ€; the Youth Section of the Ukrainian Network against the Commercial Sexual Exploitation of Children; the â€œDevelopment of Democracyâ€ Centre. The complaint lists the various provisions of the Constitution, other legislation and international agreements which the Prime Ministerâ€™s remarks are so at variance with. It points out that the Ombudsperson is obliged to consider such complaints and respond to them. The complaint reads that â€œthe remarks quoted by M. Azarov are a public statement by a high-ranking public official which can be considered part of his governmental activities, this resulting in a violation of the rights and legitimate interests of an entire group of citizens, Ukrainian women. An obstruction has been created preventing women from exercising their constitutional right to take part in State governance, this also being a demonstration of direct discrimination. The authors give a detailed analysis of the discriminatory nature of such remarks and conclude by expressing the hope that the Ombudsperson will react in accordance with the law and not her political affiliations (Nina Karpachova actually held office as a National Deputy from the Party of the Regions, Azarovâ€™s party, in 2006 â€“ translator). see olso: \u0095 So what is positive in restricting womenï¿½s right to take part in government? \u0095 Ukraine lagging behind in number of women in high office \u0095 Ukrainian women vs. Azarov \u0095 Prime Minister Azarov to answer charges of discrimination in court \u0095 Azarov: Carrying out reform is not a womanï¿½s matter",
             "contentTitle"=>"",
             "timestamp"=>"2011-09-30T17:55:26.097Z",
             "contentBodyHeading6"=>[""],
             "contentBodyHeading5"=>["Womenï¿½s rights"],
             "contentBodyHeading4"=>
              ["Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group"],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>[""],
             "contentBodyHeading1"=>
              ["Complaint to Human Rights Ombudsperson over Azarovï¿½s discriminatory comments"]}]}},
       {"groupValue"=>"http://khpg.org/en/index.php?do=print&id=1269043679",
        "doclist"=>
         {"numFound"=>1,
          "start"=>0,
          "docs"=>
           [{"digest"=>"sha1:SKYAOLCCSCWA6PQVKT5DBXO6CAOIM5B3",
             "filename"=>
              "ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904153338-01208-crawling04.us.archive.org-6682.warc.gz",
             "length"=>2037,
             "mimetype"=>"text/html",
             "originalUrl"=>
              "http://khpg.org/en/index.php?do=print&id=1269043679",
             "readerIdentifier"=>
              "/cul/cul1/ldpd/mellon_web_resources_collection/human_rights/asf-indexer-qad/archive-it_copy/2010_09/ARCHIVEIT-1068-QUARTERLY-HUHLCT-20100904153338-01208-crawling04.us.archive.org-6682.warc.gz",
             "recordDate"=>"20100904153350",
             "recordIdentifier"=>
              "20100904153350/http://khpg.org/en/index.php?do=print&id=1269043679",
             "statusCode"=>"200",
             "dateOfCaptureYYYY"=>"2010",
             "dateOfCaptureYYYYMM"=>"201009",
             "dateOfCaptureYYYYMMDD"=>"20100904",
             "archivedUrl"=>
              "http://wayback.archive-it.org/1068/20100904153350/http://khpg.org/en/index.php?do=print&id=1269043679",
             "contentBody"=>
              "Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group http://khpg.org.index.php?id=1269043679 Womenï¿½s rights Azarov: Carrying out reform is not a womanï¿½s matter 20.03.10 | www.unian.net Prime Minister Mykola Azarov stated on Friday, after presenting the new Governor of the Dnipropetrovsk region, Oleksandr Vilkul, that â€œcarrying out reform in Ukraine is not a womanâ€™s matterâ€. â€œSome say that our government is large, others that it doesnâ€™t have any women in it, thereâ€™s nobody to look at during a Cabinet of Ministers meeting. The most boring people. With all due respect to women, it is not a womanâ€™s matter to carry out reformsâ€.Â  He claimed that in the new government people had been chosen who can work 16 hours a day â€œwithout weekends and days offâ€, can take responsibility and are not afraid to say no to the leadership.",
             "contentTitle"=>"",
             "timestamp"=>"2011-09-30T19:48:27.485Z",
             "contentBodyHeading6"=>[""],
             "contentBodyHeading5"=>["Womenï¿½s rights"],
             "contentBodyHeading4"=>
              ["Human Rights in Ukraine. Information website of the Kharkiv Human Rights Protection Group"],
             "contentBodyHeading3"=>[""],
             "contentBodyHeading2"=>[""],
             "contentBodyHeading1"=>
              ["Azarov: Carrying out reform is not a womanï¿½s matter"]}]}}]}},
 "facet_counts"=>
  {"facet_queries"=>{},
   "facet_fields"=>
    {"domain"=>
      ["www.wluml.org",
       551111,
       "awid.org",
       88075,
       "www.asiapacificforum.net",
       29804,
       "www.omct.org",
       14120,
       "www.cdhr.info",
       7457,
       "www.nchregypt.org",
       6579,
       "www.amnesty.org",
       6101,
       "www.frontlinedefenders.org",
       6068,
       "www.we-change.org",
       5155,
       "www.equalityhumanrights.com",
       4629,
       "www.humanrights.asia",
       3881],
     "geographic_focus__facet"=>
      ["[Global focus]",
       676749,
       "Asia",
       34863,
       "Pacific Ocean",
       29804,
       "Egypt",
       8127,
       "Saudi Arabia",
       7472,
       "Iran",
       7208,
       "Great Britain",
       4630,
       " [043 CODE NOT FOUND IN MARC LIST]",
       3844,
       "Australia",
       3335,
       "Northern Ireland",
       3016,
       "Namibia",
       2995],
     "organization_based_in__facet"=>
      ["England",
       560698,
       "No place, unknown, or undetermined",
       86897,
       "Australia",
       33139,
       "Switzerland",
       17527,
       "United States",
       9285,
       "United Kingdom",
       8358,
       "Egypt",
       8207,
       "Ireland",
       6459,
       "Iran",
       5163,
       "New York (State)",
       3999,
       "China",
       3884],
     "organization_type__facet"=>
      ["Non-governmental organizations",
       755363,
       "National human rights institutions",
       19616,
       "Other organization types",
       1083,
       "Individual site creators",
       153],
     "language__facet"=>
      ["English",
       773972,
       "French",
       669939,
       "Arabic",
       573894,
       "Spanish",
       122628,
       "Russian",
       8803,
       "Persian",
       6683,
       "Hungarian",
       1265,
       "Turkish",
       834,
       "Georgian",
       761,
       "Ukrainian",
       538,
       "Italian",
       527],
     "contentMetaLanguage"=>
      ["en",
       4359,
       "english",
       208,
       "enus",
       27,
       "us",
       27,
       "es",
       14,
       "fr",
       13,
       "ar",
       12,
       "de",
       9,
       "sv",
       8,
       "el",
       4,
       "nl",
       4],
     "creator_name__facet"=>
      ["Women Living Under Muslim Laws (Organization)",
       551111,
       "Association for Women's Rights in Development",
       88075,
       "Asia Pacific Forum of National Human Rights Institutions",
       29804,
       "World Organisation Against Torture",
       14120,
       "Center for Democracy & Human Rights in Saudi Arabia",
       7457,
       "Majlis al-QawmiÌ„ li-HÌ£uquÌ„q al-InsaÌ„n (Egypt)",
       6579,
       "Amnesty International. International Secretariat",
       6101,
       "Front Line (Organization)",
       6068,
       "One Million Signatures Demanding Changes to Discriminatory Laws (Campaign)",
       5155,
       "Great Britain. Equality and Human Rights Commission",
       4629,
       "Asian Human Rights Commission",
       3881],
     "mimetype"=>
      ["html",
       1064299,
       "text",
       1064299,
       "texthtml",
       1029194,
       "charset",
       1014509,
       "8",
       948794,
       "utf",
       948794,
       "charsetutf",
       913152,
       "0",
       49322,
       "texthtmlcharsetutf",
       34820,
       "charsetwindow",
       15531,
       "window",
       15531],
     "dateOfCaptureYYYY"=>["2011", 581788, "2010", 476491, "2009", 6195]},
   "facet_dates"=>{},
   "facet_ranges"=>{}}}

   end
end